# vim: ft=yaml.ansible
---

# - name: Install auto-cpufreq and thermald
#   ansible.builtin.include_role:
#     name: pacman
#     tasks_from: install_pkg
#   vars:
#     packages:
#       - auto-cpufreq
#       - thermald

# - name: Enable auto-cpufreq service
#   become: true
#   ansible.builtin.systemd:
#     name: 'auto-cpufreq.service'
#     daemon_reload: true
#     enabled: true
#     state: started

- name: Create logind config dir
  become: true
  ansible.builtin.file:
    path: '/etc/systemd/logind.conf.d'
    state: directory
    mode: '755'

- name: Apply logind configs
  become: true
  ansible.builtin.template:
    src: 'logind/{{ item }}.j2'
    dest: '/etc/systemd/logind.conf.d/{{ item }}'
    mode: '644'
  vars:
    templates:
      - lid.conf
      - keys.conf
  loop: '{{ templates }}'

- name: Disable wakeup triggers for defined USB devices
  become: true
  ansible.builtin.template:
    src: 'udev/50-wakeup-triggers-disable.rules.j2'
    dest: '/etc/udev/rules.d/50-wakeup-triggers-disable.rules'
    mode: '644'
  when: power_management.disable_wakeup_triggers is defined

# TODO: acpi wakeup
#
# - name: Create tmpfiles.d config dir
#   become: true
#   ansible.builtin.file:
#     path: '/etc/tmpfiles.d'
#     state: directory
#     mode: '755'
#
# - name: Apply tmpfiles.d configs
#   become: true
#   ansible.builtin.template:
#     src: 'tmpfiles.d/{{ item }}.j2'
#     dest: '/etc/tmpfiles.d/{{ item }}'
#     mode: '644'
#   vars:
#     templates:
#       - disable-usb-wake.conf
#   loop: '{{ templates }}'
