# vim: ft=yaml.ansible
---

- name: Install kubectl and krew
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - kubectl
      - krew-bin
      - kustomize
      - kubectl-convert-bin

- name: List installed krew plugins
  ansible.builtin.shell:
    executable: 'bash'
    cmd: 'kubectl krew update && kubectl krew list'
  changed_when: false
  register: krew_list_result

- name: Install krew plugins
  vars:
    plugins: '{{ [krew_plugins] | flatten | difference(krew_list_result.stdout_lines) }}'
  ansible.builtin.command:
    cmd: 'kubectl krew install {{ plugins | join(" ") }}'
  register: krew_install_result
  changed_when: (plugins | length) > 0
  when: krew_plugins is defined and (krew_plugins | length) > 0 and (plugins | length) > 0

- name: Upgrade krew plugins
  ansible.builtin.command:
    cmd: 'kubectl krew upgrade'
  register: krew_upgrade_result
  changed_when: '"Upgraded" in krew_upgrade_result.stdout'
