# vim: ft=yaml.ansible
---

- name: Install firefox and dependencies
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages:
      - firefox
      - firefox-i18n-en-us
      - firefox-i18n-kk
      - firefox-i18n-ru
      - hunspell
      - hunspell-en_us
      - hunspell-ru
      - hyphen
      - hyphen-en
      - hyphen-ru
      - firefox-tridactyl-native-bin
      - xdg-desktop-portal
      - firefox-pwa

- name: Apply profile.d
  become: true
  ansible.builtin.template:
    src: 'firefox/{{ item }}'
    dest: '/etc/profile.d/{{ item | splitext | first }}'
    mode: '644'
  with_items:
    - 80-firefox.sh.j2
