# vim: ft=yaml.ansible
---

- name: Install firefox and dependencies
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - firefox
      - firefox-i18n-en-us
      - firefox-i18n-kk
      - firefox-i18n-ru
      - hunspell
      - hunspell-en_us
      - hunspell-ru
      - hyphen
      - hyphen-en
      - hyphen-ru
      - firefox-tridactyl-native-bin
      - xdg-desktop-portal-gtk
