# vim: ft=yaml.ansible
---

- name: install needrestart
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - needrestart  # restart services after libraries update
      - iucode-tool  # detect ucode

- name: ensure that hook dir exists
  become: true
  ansible.builtin.file:
    path: '/etc/pacman.d/hooks'
    state: directory
    mode: '755'

- name: apply needrestart pacman hook
  become: true
  ansible.builtin.template:
    src: 'needrestart/zz-needrestart.hook.j2'
    dest: '/etc/pacman.d/hooks/zz-needrestart.hook'
    mode: '644'
