# vim: ft=yaml.ansible
---

- name: install plasma-desktop
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - plasma-desktop
      - plasma-wayland-session
      - sddm
      - sddm-kcm
      - breeze
      - breeze-gtk
      - breeze-icons
      - breeze-grub  # TODO: set grub theme
      - kdeplasma-addons
      - konsole
      - dolphin
      - partitionmanager
      - ksystemlog
      - kcron
      - ksnip
      - ark
      - kfind
      - krename
      - kwalletmanager
      - yakuake
      - kdialog
      - print-manager
      - filelight
      - kcharselect

- name: enable SDDM
  become: true
  ansible.builtin.systemd:
    name: 'sddm.service'
    daemon_reload: true
    enabled: true
