# vim: ft=yaml.ansible
---

- name: install plasma-desktop
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - plasma-desktop
      - plasma-wayland-session
      - sddm  # TODO: wayland version, auto-unlock kwallet
      - sddm-kcm
      - breeze
      - breeze-gtk
      - breeze-icons
      - breeze-grub  # TODO: set grub theme
      - kdeplasma-addons
      - bluedevil
      - konsole
      - dolphin
      - gwenview
      - partitionmanager
      - ksystemlog
      - kcron
      - ksnip
      - ark
      - kfind
      - krename
      - kwalletmanager
      - yakuake
      - kdialog
      - print-manager
      - filelight
      - kcharselect

- name: create SDDM config dir
  become: true
  ansible.builtin.file:
    dest: '/etc/sddm.conf.d'
    state: directory
    mode: '755'

- name: apply default SDDM config
  become: true
  ansible.builtin.template:
    src: 'plasma-desktop/00-default.conf.j2'
    dest: '/etc/sddm.conf.d/00-default.conf'
    mode: '644'

- name: rotate second monitor
  become: true
  ansible.builtin.template:
    src: 'plasma-desktop/Xsetup.j2'
    dest: '/usr/share/sddm/scripts/Xsetup'
    mode: '755'

- name: enable SDDM
  become: true
  ansible.builtin.systemd:
    name: 'sddm.service'
    daemon_reload: true
    enabled: true
