# vim: ft=yaml.ansible
---

- name: install plasma-desktop
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - plasma-desktop
      - konsole
      - dolphin
      - patitionmanager
      - ksystemlog
      - kcron
      - ark
      - kfind
      - krename
      - kwalletmanager
      - yakuake
      - kdialog
      - print-manager
      - filelight
      - kcharselect
