# vim: ft=yaml.ansible
---

- name: Add wheel group to sudoers
  become: true
  community.general.sudoers:
    name: '50-wheel'
    group: wheel
    nopassword: false
    runas: 'ALL:ALL'
    commands: ALL

- name: Apply sudoers.d
  become: true
  ansible.builtin.template:
    src: 'sudoers/{{ item }}.j2'
    dest: '/etc/sudoers.d/{{ item }}'
    mode: '600'
  with_items:
    - '10-env_keep'
    - '10-insults'
    - '70-pwfeedback'
