# vim: ft=yaml.ansible
---

- name: apply sudoers.d
  become: true
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '/etc/sudoers.d/{{ item | basename | splitext | first }}'
    mode: '644'
  with_items:
    - sudoers/insults.j2
    - sudoers/env_keep.j2
