# vim: ft=yaml.ansible
---

- name: apply sudoers.d
  become: true
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '/etc/sudoers.d/{{ item | basename | splitext | first }}'
    mode: '644'
  loop: '{{ [role_path, "templates/sudoers/*.j2"] | path_join | fileglob }}'
