# vim: ft=yaml.ansible
---

- name: Apply profile.d
  become: true
  ansible.builtin.template:
    src: 'profile/{{ item }}.j2'
    dest: '/etc/profile.d/{{ item }}'
    mode: '644'
  with_items:
    - 00-setup.sh
    - 10-xdg.sh
    - 15-xdg-base-dir-override.sh
    - 20-path.sh
    - 30-diffprog.sh
    - 30-editor.sh
    - 30-pager.sh
    - 70-fzf.sh
    - 70-kube.sh
    - zo-import-env.sh
    - zz-cleanup.sh
