# vim: ft=yaml.ansible
---

- name: Define hostname
  become: true
  ansible.builtin.copy:
    content: "{{ hostname | mandatory }}\n"
    dest: '/etc/hostname'
    mode: '644'

- name: Apply hosts file
  become: true
  ansible.builtin.template:
    src: 'hostname/hosts.j2'
    dest: '/etc/hosts'
    mode: '644'
