# vim: ft=yaml.ansible
---

- hosts: local
  roles:
    - archconfig_user
    - timedate
    - locale
    - hostname
    - ssd
    - sudoers
    - pacman
    - rust
    - paru
    - systemd
    - vconsole
    - solokeys
    - firewalld
    - nextdns
      # TODO: wireguard
    - pkgfile
    - realtime
    - profile
    - ssh
    # - ly
    - kmscon
    - tmux
    - docker
    - kube-tools
    - apps_cli
      # hardware
    - audio
    - bluetooth
    - intel_graphics
      # gui
    - fonts
    - theme
    - sway
    - apps_gui
    - tor
    - firefox
    - steam

# TODO: use tags to split vsconsole only and gui only tasks. Eg. tor(cli) and torbrowser-launcher(gui)
