# vim: ft=yaml.ansible
---

- name: Config
  hosts: all
  roles:
    - prepare_facts
    - archconfig_user
    - user
    - timedate
    - locale
    - hostname
    - disk
    - sudoers
    - pacman
    - fwupd
    - devtools
    - kernels
    - needrestart
    - mkinitcpio
    - bootloader
    - swap
    - zsh
    - firewalld
    - network
    - vconsole
    # TODO: wireguard
    - realtime
    - profile
    - power_management
    # - ddcutil  # NOTE: Powerdevil stops to manage brightness of internal monitor... >:-[
    - smartcard
    - ssh
    # - ly
    # - kmscon
    - tmux
    - docker
    - kube_tools
    - pixelserv_tls
    - apps_cli

    # hardware
    - audio
    - bluetooth
    # - intel_graphics
    - amd_graphics

    # gui
    - fonts
    # - theme
    # - sway
    - plasma_desktop

    - apps_gui

    - flatpak
    - tor
    - firefox
    - games
    - printer
    - scanner
    - virtualization
    - snapper  # should be last (do not create snapshots when ansible install packages)

# TODO: use tags to split vsconsole only and gui only tasks. Eg. tor(cli) and torbrowser-launcher(gui)
# TODO: podman, buildah, skopeo, ... instead of (or alongside) docker
# TODO: install wireshark and add user to group wireshark
# TODO: use tags or variables to distinguish between gui/cli
