# vim: ft=yaml.ansible
---

- hosts: local
  roles:
    - archconfig_user
    - timedate
    - locale
    - vconsole
    - hostname
    - ssd
    - sudoers
    - pacman
    - firewalld
    - pkgfile
    - realtime
    - profile
    - ssh
    - ly
    - kmscon
    - tmux
    - apps_cli
      # hardware
    - audio
    - bluetooth
    - intel_graphics
      # gui
    - fonts
    - theme
    - sway
    - apps_gui
