# vim: ft=yaml.ansible
---

- hosts: local
  roles:
    - archconfig_user
    - user
    - timedate
    - locale
    - hostname
    - ssd
    - sudoers
    - pacman
    - rust
    - paru
    - kernels
    - mkinitcpio
    - bootloader
    - zram
    - systemd
    - zsh
    - snapper
    - networkmanager
    - vconsole
    - solokeys
    - firewalld
    - nextdns
      # TODO: wireguard
    - pkgfile
    - realtime
    - profile
    - ssh
    # - ly
    # - kmscon
    - tmux
    - docker
    - kube-tools
    - apps_cli
      # hardware
    - audio
    - bluetooth
    - intel_graphics
      # gui
    - fonts
    # - theme
    # - sway
    - plasma-desktop
    - apps_gui
    - tor
    - firefox
    - steam
      # WARN: neet to refactor
    - printer

# TODO: use tags to split vsconsole only and gui only tasks. Eg. tor(cli) and torbrowser-launcher(gui)
