# vim: ft=yaml.ansible
---

- hosts: local
  roles:
    - archconfig_user
    - user
    - timedate
    - locale
    - hostname
    - ssd
    - sudoers
    - pacman
    - fwupd
    - devtools
    - kernels
    - needrestart
    - mkinitcpio
    - bootloader
    - zram
    - systemd
    - zsh
    - networkmanager
    - vconsole
    - firewalld
    - nextdns
    # TODO: wireguard
    - realtime
    - profile
    - smartcard
    - ssh
    # - ly
    # - kmscon
    - tmux
    - docker
    - kube-tools
    - pixelserv-tls
    - apps_cli
    # hardware
    - audio
    - bluetooth
    - intel_graphics
    # gui
    - fonts
    # - theme
    # - sway
    - plasma-desktop
    - apps_gui
    - flatpak
    - tor
    - firefox
    - games
    # WARN: neet to refactor
    - printer
    - avahi
    - samba
    - virtualization
    - snapper  # should be last (do not create snapshots when ansible install packages)

# TODO: use tags to split vsconsole only and gui only tasks. Eg. tor(cli) and torbrowser-launcher(gui)
# TODO: podman, buildah, skopeo, ... instead of docker
# TODO: install wireshark and add user to group wireshark
