---

all:
  hosts:
    local:
      ansible_python_interpreter: auto_silent
      ansible_connection: local
  vars:
    archconfig:
      user:
        name: archconfig
        home: /var/lib/archconfig
