---

all:
  hosts:
    local:
      ansible_python_interpreter: auto_silent
      ansible_connection: local
  vars:
    archconfig_user:
      name: archconfig
      home: /var/lib/archconfig
    timezone: Asia/Almaty
    hostname: arch-s15
    locales:
      - en_US.UTF-8 UTF-8
      - ru_RU.UTF-8 UTF-8
      - kk_KZ.UTF-8 UTF-8
    vconsole:
      keymap: ru
      font: ter-p22n
    ssd: true
    mirrorlist_timeout_sec: 86400
    pacman_ignore_pkg:
      - linux-zen
      - linux-lts
      - btrfs-progs
      - cryptsetup
      - device-mapper
      - dmraid
      - lvm2
      - mdadm
      - mkinitcpio
      - mkinitcpio-busybox
      - systemd
      - ostree
    # TODO: manage kernels and bootloader
    ly: true
    kmscon: true
    ssh_keys:
      - path: 'id_ed25519'
        mode: '400'
      - path: 'id_ed25519.pub'
        mode: '444'
    xdg:
      data_dirs:
        - /usr/share
        - /usr/local/share
      config_dirs:
        - /etc/xdg
      home:
        config: '$HOME/.config'
        cache: '$HOME/.cache'
        data: '$HOME/.local/share'
        state: '$HOME/.local/state'
    profile:
      editor: nvim
      path_pre:
        - '$HOME/.local/bin'
        - '$XDG_CONFIG_HOME/composer/vendor/bin'
        - '$HOME/.gem/ruby/3.0.0/bin'
        - '$HOME/.yarn/bin'
        - '$HOME/Android/Sdk/tools/bin'
        - '$HOME/Android/Sdk/emulator'
        - '$HOME/go/bin'
        - '$HOME/.dotnet/tools'
        - '$HOME/Flutter/bin'
        - '$HOME/.krew/bin'
        - '$XDG_DATA_HOME/npm/bin'
        - '$XDG_DATA_HOME/cargo/bin'
      # path_post:
    apps:
      cli:
        - fwupd  # update firmware
        - ripgrep  # modern grep
        - lsd  # modern ls
        - fd  # modern find
        - jq  # json query processor
        - jless  # json viewer like less
        - fzf  # fuzzy menu
        - zoxide  # jump to directory like z
        - vivid  # generate console colors
        - bat  # modern cat
        - git-delta  # modern diff
        - pacman-contrib  # libalpm utils
        - namcap  # package analyzer
        - expac  # query pacman database
        - s-tui  # stress testing
        - upower  # power devices info
        - imagemagick  # image processing
        - ffmpeg  # video processing
        - yt-dlp  # download youtube videos
        - source-highlight  # highlight source code in console pipline
        - udisks2  # disk management
        - lvm2    # needed to add these here because they are
        - mdadm   # ... dependencies of udisks2 and they are
        - dmraid  # ... ignored by pacman in IgnorePkg
          # TODO: find a way to replace chezmoi with ansible
        - chezmoi  # dotfiles manager
      gui:
        - alacritty  # terminal emulator
        - imv  # image viewer
        - mpv  # multimedia player
