---

all:
  hosts:
    local:
      ansible_python_interpreter: auto_silent
      ansible_connection: local
  vars:
    archconfig_user:
      name: archconfig
      home: /var/lib/archconfig
    user:
      name: zhanibek
      shell: /usr/bin/zsh
      password: '{{ user_password | password_hash("sha512") }}'
    # extra_users:
    timezone: Asia/Almaty
    hostname: arch-s15
    extra_hosts:
      - ip: 13.48.233.100
        name: cybernation.pro
      - ip: 13.51.15.67
        name: cybernation.pro
    locales:
      - en_US.UTF-8 UTF-8
      - ru_RU.UTF-8 UTF-8
      - kk_KZ.UTF-8 UTF-8
    vconsole:
      keymap: ru
      font: ter-p22n
    acpi_wakeup: XHCI
    ssd: true
    # pacman_ignore_pkg:
    #   - linux-zen
    #   - linux-lts
    #   - btrfs-progs
    #   - cryptsetup
    #   - device-mapper
    #   - dmraid
    #   - lvm2
    #   - mdadm
    #   - mkinitcpio
    #   - mkinitcpio-busybox
    #   - systemd
    #   - ostree
    kernels: zen,lts
    ucode: intel-ucode
    swap: true
    mkinitcpio:
      modules: 'crc32c-intel intel_agp i915'
    #   binaries: ''
    #   files: ''
      hooks: 'base consolefont udev autodetect modconf block filesystems keyboard keymap fsck'
      compression: 'zstd'
    bootloader:
      grub: true
      # part_selector: '{{ part_selector }}'
      # fstype: 'btrfs'
      # subvol_selector: 'subvol=/@'
      # kernel_params: 'sysrq_always_enabled=1 snd_hda_codec_hdmi.enable_silent_stream=0'
      kernel_params: 'sysrq_always_enabled=1'
      timeout: 1
      timeout_style: hidden
      # editor: true
    multilib: true
    ly: false
    kmscon: false
    ssh_keys:
      - path: 'id_ed25519'
        mode: '400'
      - path: 'id_ed25519.pub'
        mode: '444'
    xdg:
      data_dirs:
        - /usr/share
        - /usr/local/share
      config_dirs:
        - /etc/xdg
      home:
        config: '$HOME/.config'
        cache: '$HOME/.cache'
        data: '$HOME/.local/share'
        state: '$HOME/.local/state'
    profile:  # TODO: refactor profile templates
      editor: nvim
      path_pre:
        - '$HOME/.local/bin'
        - '$XDG_CONFIG_HOME/composer/vendor/bin'
        - '$HOME/.gem/ruby/3.0.0/bin'
        - '$HOME/.yarn/bin'
        - '$HOME/Android/Sdk/tools/bin'
        - '$HOME/Android/Sdk/emulator'
        - '$HOME/go/bin'
        - '$HOME/.dotnet/tools'
        - '$HOME/Flutter/bin'
        - '$HOME/.krew/bin'
        - '$XDG_DATA_HOME/npm/bin'
        - '$XDG_DATA_HOME/cargo/bin'
      # path_post:
    nextdns_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36623966633333346237303138623938623633306364326164633633303633616264333137663737
          6639626165346530396461383137393131326136663033350a336637653434663562333965303035
          63383762396638393835333430343734376236366366353037646335666165666536636338653065
          3766616366663335390a316539313131323431663662376239346362306338653261396164373362
          3536
    krew_plugins:
      - ctx
      - ns
      - neat
    apps:
      cli:
        - base
        - base-devel
        - iptables-nft
        - linux-firmware
        - efibootmgr
        - networkmanager
        - polkit
        - btrfs-progs
        - man-db
        - man-pages
        - ansible
        - git
        - exfat-utils
        - neovim  # neovim
        - python-pynvim  # python 3 provider for neovim
        - fwupd  # update firmware
        - ripgrep  # modern grep
        - lsd  # modern ls
        - fd  # modern find
        - jq  # json query processor
        - go-yq  # yaml query processor
        - jless  # json viewer like less
        - fzf  # fuzzy menu
        - zoxide  # jump to directory like z
        - direnv  # shell extension that manages your env
        - vivid  # generate console colors
        - bat  # modern cat
        - nvimpager  # pager using neovim
        - git-delta  # modern diff
        - git-extras
        - pacman-contrib  # libalpm utils
        - namcap  # package analyzer
        - expac  # query pacman database
        - s-tui  # stress testing
        - upower  # power devices info
        - yt-dlp  # download youtube videos
        - zip
        - unzip
        - source-highlight  # highlight source code in console pipline
        - udisks2  # disk management
        - lvm2    # needed to add these here because they are
        - mdadm   # ... dependencies of udisks2 and they are
        - dmraid  # ... ignored by pacman in IgnorePkg
          # TODO: find a way to replace chezmoi with ansible
        - chezmoi  # dotfiles manager
        - nmap  # port scanner
        - net-tools  # netstat and friends
        - iptables-nft  # nftables (iptables drop-in replacement)
        - bash-completion  # bash shell completions
        - dex  # execute desktop files and autostart apps
        - dust  # modern du
        - duf  # modern df
        - btop  # modern htop/top
        - brightnessctl  # backlight control
        - libqalculate  # cli qalculator
        - bind  # dns utils
        - inetutils  # network utils
        # - systemd-boot-pacman-hook  # hook to update systemd-boot on update
        - tealdeer  # tldr
        - i7z  # intel cpu reporting tool
          ### dev
        - go
        - nodejs
        - npm
        - nim
        - clang
        - asp  # arch build sources management
        - devtools  # arch package build tools
        - namcap  # arch package analysis
        - python-aiohttp  # needed for codestats-relay
        - aws-cli
        - php
        - composer
          ## lsp
        - lua-language-server
        - bash-language-server
        - shellcheck
        - ansible-language-server
        - ansible-lint
          ### libs
        - libxcrypt-compat  # nplusplus (Steam) dependency
      gui:
        # - alacritty  # terminal emulator
        # - imv  # image viewer
        - mpv  # multimedia player
        - mpv-mpris  # mpris plugin for mpv
        # - lxqt-policykit  # policykit agent
        - qalculate-qt  # qt frontend for qalculate
        - enpass-bin  # password manager
        # - zenity  # gui dialogs in scripts
        - xorg-xeyes  # xeyes, detect xwayland windows
        # - ksnip  # edit, annotate screenshots
        - code  # Visual Studio Code OSS
        # - lxqt-openssh-askpass  # ssh askpass dialog
        - telegram-desktop  # Telegram desktop client
        # - libgnomekbd  # view keyboard layout in a window
        # - dragon-drop  # drag-and-drop helper
          ### TODO: multimedia - extract to role. not belong here.
        - imagemagick  # image processing
        - ffmpeg  # video processing
        - tk  # gitk
        - gstreamer
        - gstreamer-vaapi
        - gst-libav
        - gst-plugins-base
        - gst-plugins-bad
        - gst-plugins-ugly
        - gst-plugins-good
        - gst-plugin-pipewire
