# vim: ft=yaml.ansible
---

- name: Set up user
  become: true
  ansible.builtin.user:
    name: '{{ user.name | mandatory }}'
    groups: '{{ user.groups | default([]) | union(["wheel"]) }}'
    append: '{{ user.append | default(true) }}'
    shell: '{{ user.shell | default(omit) }}'
    comment: '{{ user.comment | default(omit) }}'
    create_home: '{{ user.create_home | default(true) }}'
    home: '{{ user.home | default(omit) }}'
    system: false
  no_log: true
