# vim: ft=yaml.ansible
---

- name: Set up user
  become: true
  ansible.builtin.user:
    name: '{{ user.name | mandatory }}'
    password: '{{ user.password | mandatory | password_hash("sha512", rounds=65536) }}'
    update_password: '{{ user.update_password | default("on_create") }}'
    groups: '{{ user.groups | default([]) | union(["wheel"]) }}'
    append: '{{ user.append | default(true) }}'
    shell: '{{ user.shell | default(omit) }}'
    comment: '{{ user.comment | default(omit) }}'
    create_home: '{{ user.create_home | default(true) }}'
    home: '{{ user.home | default(omit) }}'
    system: false
  no_log: true
  register: setup_user_result

- name: Set user home dir permissions
  become: true
  ansible.builtin.file:
    path: '{{ setup_user_result.home }}'
    state: directory
    mode: '{{ user.home_mode }}'
  when: user.home_mode is defined
