# vim: ft=yaml.ansible
---

- name: 'Add user to groups: {{ user_new_groups }}'
  become: true
  ansible.builtin.user:
    append: true
    name: '{{ user.name }}'
    groups: '{{ user_new_groups }}'
