# yaml-language-server: $schema=./vars.schema.yml
---

ansible_become_pass: '{{ lookup("ansible.builtin.env", "AAC_USER_PASSWORD") }}'

bootloader:
  # grub_package: grub-silent  # silent boot
  timeout: 1
  timeout_style: hidden
  # kernel_params:
    # # disable watchdog
    # - 'nowatchdog'
    # - 'modprobe.blacklist=sp5100_tco'
    # - 'nmi_watchdog=0'
    # # sdma0 timeout workaround
    # - 'amdgpu.vm_update_mode=3'
    # # silent boot
    # - 'vt.global_cursor_default=0'
    # - 'rd.systemd.show_status=false'
    # - 'loglevel=3'
    # - 'rd.udev.log-priority=3'

disk:
  ssd: true
  scrub:
    - '/'

kernels:
  list:
    - linux
    - linux-lts
  headers: true
  extra_modules:
    # extra firmware
    - upd72020x-fw
  module_blacklist:
    # disable inadequately loud beep on lenovo thinkpads
    - pcspkr
    - snd_pcsp

mkinitcpio:
  modules:
    - usbhid
    - xhci_hcd
    - amdgpu
  binaries:
    - setfont
  compression: zstd
  modules_decompress: true

power_management:
  lid_switch: suspend
  suspend_key: suspend
  power_key: suspend
  power_key_long: poweroff
  ec_no_wakeup: false
  disable_wakeup_triggers:
    - comment: 'Thinkpad T16 touchpad'
      name: 'ELAN0688:00'
    # - comment: 'Thinkpad T16 trackpoint'
    #   description: 'i8042 AUX port'
    # - comment: 'Thinkpad T16 keyboard'
    #   description: 'i8042 KBD port'
    - comment: 'Logitech unifying receiver'
      vendor_id: '046d'
      product_id: 'c52b'
    - comment: 'Drop Preonic keyboard'
      vendor_id: '03a8'
      product_id: 'a649'
    - comment: 'ZSA Moonlander keyboard'
      vendor_id: '3297'
      product_id: '1969'

hostname: arch-t16

timezone: Asia/Almaty

locales:
  list:
    - en_US.UTF-8 UTF-8
    - ru_RU.UTF-8 UTF-8
    - kk_KZ.UTF-8 UTF-8
  lang: en_US.UTF-8

user:
  name: zhanibek
  shell: /usr/bin/zsh
  password: '{{ lookup("ansible.builtin.env", "AAC_USER_PASSWORD") }}'
  home_mode: '751'

swap:
  zram: true
  swappiness: 10
  hibernation:
    type: file
    path: '/swap/swapfile'

vconsole:
  keymap: ru
  font: ter-p22n

ssh:
  ssh_keys:
    - name: 'id_ed25519.pub'
      content: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGOzFHEhf9c5Z1t1AZm1fb3PQQlGsBXlhmUI/JB8ZXC+'

network:
  ip_forwarding: true
  nextdns_id: '{{ lookup("ansible.builtin.env", "AAC_NEXTDNS_ID") }}'
  wifi_powersave: false
  wifi_backend: 'wpa_supplicant'

kube:
  krew:
    plugins:
      - ctx
      - ns
      - neat

apps:
  flatpak:
    - com.redis.RedisInsight
    - com.obsproject.Studio
    - com.obsproject.Studio.Plugin.BackgroundRemoval
    - com.obsproject.Studio.Plugin.GStreamerVaapi
    - com.obsproject.Studio.Plugin.OBSVkCapture
    - com.obsproject.Studio.Plugin.DroidCam
    - com.usebruno.Bruno


pacman:
  reflector: false

dev_tools:
  rust:
    toolchains:
      - stable
      - nightly
    components:
      - cargo
      - clippy
      - rust-analyzer
      - rust-docs
      - rust-src
      - rust-std
      - rustc
      - rustfmt
