# vim: ft=yaml.ansible
---

- name: Add trust anchor
  become: true
  ansible.builtin.command:
    argv: ['trust', 'anchor', '/var/cache/pixelserv/ca.crt']
  changed_when: true
  notify:
    - Extract compatibility trust certificates
    - Update ca trust

- name: Extract compatibility trust certificates
  become: true
  ansible.builtin.command:
    argv: ['trust', 'extract-compat']
  changed_when: true

- name: Update ca trust
  become: true
  ansible.builtin.command:
    argv: ['update-ca-trust']
  changed_when: true
