# vim: ft=yaml.ansible
---

- name: Install zram generator
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages: zram-generator

- name: Zram swap
  become: true
  community.general.ini_file:
    dest: '/etc/systemd/zram-generator.conf'
    section: 'zram0'
    allow_no_value: true
    mode: '644'

- name: Zram swap service
  become: true
  ansible.builtin.systemd:
    name: 'systemd-zram-setup@zram0.service'
    daemon_reload: true
    enabled: true
