# vim: ft=yaml.ansible
---

- name: Install steam, games and related software
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages:
      - steam
      - steam-native-runtime
      - lutris
      - umu-launcher
      - aur/protontricks
      - python-steam
      - protonup-qt
      - sc-controller  # steam controller gui
      - game-devices-udev
      - gamemode
      - lib32-gamemode
      - gamescope
      - mangohud
      - lib32-mangohud
      - gzdoom
      - zandronum
      - doomseeker
      - doomrunner
      - nudoku
      - aur/prismlauncher
      - glfw-wayland
      - pokerth
      - mrboom
      - granatier
      - puzzles  # simon tatham's puzzles collection
      - crack-attack
      - crack-attack-sounds

      # dependencies
      - libxcrypt-compat  # nplusplus (Steam) dependency

- name: Copy gamemode script
  become: true
  ansible.builtin.template:
    src: 'games/gamemode_script.j2'
    dest: '/usr/bin/gamemode_script'
    mode: '755'

- name: Add gamemode_script to sudoers
  become: true
  community.general.sudoers:
    name: '90-gamemode'
    group: gamemode
    nopassword: true
    runas: 'ALL:ALL'
    commands: /usr/bin/gamemode_script

- name: Apply gamemode config
  become: true
  ansible.builtin.template:
    src: 'games/gamemode.ini.j2'
    dest: '/etc/gamemode.ini'
    mode: '644'

- name: Add user to input and gamemode group
  ansible.builtin.include_role:
    name: user
    tasks_from: user_add_group
  vars:
    user_new_groups:
      - input
      - gamemode

- name: Firewall rules for steam streaming
  ansible.builtin.include_role:
    name: firewalld
    tasks_from: add_rule
  vars:
    firewalld_services:
      - steam-streaming
