# vim: ft=yaml.ansible
---

- name: Install steam, games and related software
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages:
      - steam
      - steam-native-runtime
      - lutris
      - aur/protontricks
      - protonup-qt
      - sc-controller  # steam controller gui
      - game-devices-udev
      - gamemode
      - lib32-gamemode
      - libstrangle  # fps limiter
      - gamescope
      - mangohud
      - lib32-mangohud
      - gzdoom
      - zandronum
      - doomseeker
      - doomrunner
      - nudoku
      - prismlauncher
      - glfw-wayland
      - pokerth
      - mrboom

      # dependencies
      - libxcrypt-compat  # nplusplus (Steam) dependency

- name: Apply gamemode config
  become: true
  ansible.builtin.template:
    src: 'games/gamemode.ini.j2'
    dest: '/etc/gamemode.ini'
    mode: '644'

- name: Add user to input and gamemode group
  ansible.builtin.include_role:
    name: user
    tasks_from: user_add_group
  vars:
    new_groups:
      - input
      - gamemode

- name: Firewall rules for steam streaming
  ansible.builtin.include_role:
    name: firewalld
    tasks_from: add_rule
  vars:
    services:
      - steam-streaming
