# vim: ft=yaml.ansible
---

- name: install pixelxerv-tls
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: pixelserv-tls

- name: generate rsa private key
  become: true
  become_user: nobody
  become_method: su
  become_flags: '-s /bin/bash'
  ansible.builtin.command:
    cmd: ['/usr/bin/openssl', 'genrsa', '-out', '/var/cache/pixelserv/ca.key', '2048']
    creates: '/var/cache/pixelserv/ca.key'

- name: generate rsa private key
  become: true
  become_user: nobody
  become_method: su
  become_flags: '-s /bin/bash'
  ansible.builtin.command:
    cmd: ['/usr/bin/openssl', 'req', '-key', '/var/cache/pixelserv/ca.key', '-new', '-x509', '-days', '3650',
          '-sha256', '-extension', 'v3_ca', '-out', '/var/cache/pixelserv/ca.crt', '-subj', '/CN=Pixelserv CA']
    creates: '/var/cache/pixelserv/ca.crt'
  notify:
    - add trust anchor
