# vim: ft=yaml.ansible
---

- name: Install zram generator
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: zram-generator

- name: Zram swap
  become: true
  community.general.ini_file:
    dest: '/etc/systemd/zram-generator.conf'
    section: 'zram0'
    allow_no_value: true
    mode: '644'
  when: swap.enabled | default(true)

- name: Zram swap service
  become: true
  ansible.builtin.systemd:
    name: 'systemd-zram-setup@zram0.service'
    daemon_reload: true
    enabled: true
  when: swap.enabled | default(true)

- name: Set swappiness
  become: true
  ansible.posix.sysctl:
    name: 'vm.swappiness'
    sysctl_file: '/etc/sysctl.d/99-swappiness.conf'
    sysctl_set: true
    value: '{{ swap.swappiness | default("60") }}'
