# vim: ft=yaml.ansible
---

- name: zram swap
  become: true
  ansible.builtin.ini_file:
    dest: '/etc/systemd/zram-generator.conf'
    section: 'zram0'
    allow_no_value: true
    mode: '644'
  when: swap | default(true)

- name: zram swap service
  become: true
  ansible.builtin.systemd:
    name: 'systemd-zram-setup@zram0.service'
    daemon_reload: true
    enabled: true
  when: swap | default(true)

- name: set swappiness
  become: true
  ansible.posix.sysctl:
    name: 'vm.swappiness'
    sysctl_file: '/etc/sysctl.d/99-swappiness.conf'
    sysctl_set: true
    value: '{{ swappiness | default("60") }}'
