# vim: ft=yaml.ansible
---

- name: Create logind config dir
  become: true
  ansible.builtin.file:
    path: '/etc/systemd/logind.conf.d'
    state: directory
    mode: '755'

- name: Apply logind configs
  become: true
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '/etc/systemd/logind.conf.d/{{ item | basename | splitext | first }}'
    mode: '644'
  vars:
    templates:
      - logind/lid.conf.j2
      - logind/keys.conf.j2
  loop: '{{ templates }}'

- name: Create tmpfiles.d config dir
  become: true
  ansible.builtin.file:
    path: '/etc/tmpfiles.d'
    state: directory
    mode: '755'

- name: Apply tmpfiles.d configs
  become: true
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '/etc/tmpfiles.d/{{ item | basename | splitext | first }}'
    mode: '644'
  vars:
    templates:
      - tmpfiles.d/disable-usb-wake.conf.j2
  loop: '{{ templates }}'
