# vim: ft=yaml.ansible
---

- name: Install pixelxerv-tls
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages: pixelserv-tls

- name: Create pixelserv-tls cache dir
  become: true
  ansible.builtin.file:
    path: '/var/cache/pixelserv'
    owner: 'nobody'
    group: 'root'
    mode: '750'
    state: directory

- name: Generate rsa private key
  become: true
  become_user: '{{ archconfig_user.name | default("archconfig") }}'
  ansible.builtin.command:
    argv: ['/usr/bin/sudo', '-u', 'nobody', '--', '/usr/bin/openssl', 'genrsa', '-out', '/var/cache/pixelserv/ca.key',
           '2048']
    creates: '/var/cache/pixelserv/ca.key'

- name: Generate local certificate
  become: true
  become_user: '{{ archconfig_user.name | default("archconfig") }}'
  ansible.builtin.command:
    argv: ['/usr/bin/sudo', '-u', 'nobody', '--', '/usr/bin/openssl', 'req', '-key', '/var/cache/pixelserv/ca.key',
           '-new', '-x509', '-days', '3650', '-sha256', '-extensions', 'v3_ca', '-config', '/etc/ssl/openssl.cnf',
           '-out', '/var/cache/pixelserv/ca.crt', '-subj', '/CN=Pixelserv CA']
    creates: '/var/cache/pixelserv/ca.crt'
  notify:
    - Add trust anchor

- name: Enable pixelserv-tls service
  become: true
  ansible.builtin.systemd:
    name: 'pixelserv-tls.service'
    daemon_reload: true
    enabled: true
    state: started
