# vim: ft=yaml.ansible
---

- name: Install bluetooth packages
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - bluez
      - bluez-utils
      - bluez-hid2hci
      - bluez-cups

- name: Backup bluetooth config as .pacnew
  become: true
  ansible.builtin.copy:
    src: '/etc/bluetooth/main.conf'
    dest: '/etc/bluetooth/main.conf.pacnew'
    mode: preserve
    remote_src: true
    force: false

- name: Apply bluetooth config
  become: true
  ansible.builtin.template:
    src: 'bluetooth/bluetooth-main.conf.j2'
    dest: '/etc/bluetooth/main.conf'
    mode: '644'

- name: Enable bluetooth service
  become: true
  ansible.builtin.systemd:
    name: bluetooth.service
    enabled: true
    state: started

- name: Apply mpris-proxy service
  become: true
  ansible.builtin.template:
    src: 'bluetooth/mpris-proxy.service.j2'
    dest: '/etc/systemd/user/mpris-proxy.service'
    mode: '644'

- name: Enable mpris-proxy service
  ansible.builtin.systemd:
    daemon_reload: true
    name: mpris-proxy.service
    enabled: true
    state: started
    scope: user
