# vim: ft=yaml.ansible
---

- name: Install kmscon
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages: kmscon

- name: Disable agetty on tty2
  become: true
  ansible.builtin.systemd:
    name: 'getty@tty2.service'
    daemon_reload: true
    enabled: '{{ not (kmscon is defined and kmscon is truthy) }}'

- name: Enable kmscon on tty2
  become: true
  ansible.builtin.systemd:
    name: 'kmsconvt@tty2.service'
    daemon_reload: true
    enabled: '{{ kmscon is defined and kmscon is truthy }}'
