# vim: ft=yaml.ansible
---

- name: Create blurred background image
  ansible.builtin.command:
    cmd: 'convert {{ xdg.home.data }}/sway/bg.jpg -blur 0x50
      -virtual-pixel edge {{ xdg.home.data }}/sway/bg-blurred.jpg'
  changed_when: true
