# vim: ft=yaml.ansible
---

- name: Install ly display manager
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages: tailscale

- name: Enable talescale daemon
  become: true
  ansible.builtin.systemd:
    name: 'tailscaled'
    daemon_reload: true
    enabled: true

- name: Add tailscale0 to trusted zone
  ansible.builtin.include_role:
    name: firewalld
    tasks_from: set_zone
  vars:
    firewalld_binds:
      - interface: tailscale0
        zone: trusted
