---

- name: Install graphics drivers
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages:
      - mesa
      - lib32-mesa
      - xf86-video-amdgpu
      - vulkan-radeon
      - lib32-vulkan-radeon
      - amdvlk
      - lib32-amdvlk
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - vulkan-mesa-layers
      - lib32-vulkan-mesa-layers
      - libva-mesa-driver
      - lib32-libva-mesa-driver
      - mesa-vdpau
      - lib32-mesa-vdpau
      - nvtop
      - radeontop
      - libva-utils
      - vdpauinfo
