# vim: ft=yaml.ansible
---

- name: Install openssh
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages:
      - openssh
      - sshfs

- name: Apply ssh config
  become: true
  ansible.builtin.template:
    src: 'ssh/{{ item }}.j2'
    dest: '/etc/ssh/ssh_config.d/{{ item }}'
    mode: '644'
  with_items:
    - 30-global-config.conf

- name: Apply profile.d
  become: true
  ansible.builtin.template:
    src: 'profile/{{ item }}.j2'
    dest: '/etc/profile.d/{{ item }}'
    mode: '644'
  with_items:
    - 70-ssh-agent.sh

- name: Create user ssh dir
  ansible.builtin.file:
    path: '{{ [setup_user_result.home, ".ssh"] | path_join }}'
    state: directory
    mode: '700'

- name: Copy public keys to ssh folder
  ansible.builtin.copy:
    src: 'files/{{ item.public }}'
    dest: '{{ [setup_user_result.home, ".ssh", item.public] | path_join }}'
    mode: '444'
  loop: '{{ ssh.key_files }}'
  when: ssh.key_files is defined

- name: Copy private keys to ssh folder
  ansible.builtin.copy:
    src: 'files/{{ item.private }}'
    dest: '{{ [setup_user_result.home, ".ssh", item.private] | path_join }}'
    mode: '400'
  loop: '{{ ssh.key_files }}'
  when: ssh.key_files is defined
