# vim: ft=yaml.ansible
---

- name: Install openssh
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages: openssh

- name: Apply ssh_config
  become: true
  ansible.builtin.template:
    src: 'ssh/ssh_config.j2'
    dest: '/etc/ssh/ssh_config'
    mode: '644'

- name: Apply profile.d for ssh-agent
  become: true
  ansible.builtin.template:
    src: 'ssh/30-ssh-agent.sh.j2'
    dest: '/etc/profile.d/30-ssh-agent.sh'
    mode: '644'

- name: SSH agent systemd service file
  become: true
  ansible.builtin.template:
    src: 'ssh/{{ item }}.j2'
    dest: '/etc/systemd/user/{{ item }}'
    mode: '644'
  with_items:
    - ssh-agent.service
    - ssh-agent-restart.service

- name: Start ssh agent service
  ansible.builtin.systemd:
    name: 'ssh-agent'
    daemon_reload: true
    enabled: true
    state: started
    scope: user

- name: Start ssh agent service
  ansible.builtin.systemd:
    name: 'ssh-agent-restart'
    daemon_reload: true
    enabled: true
    scope: user

- name: Create user ssh dir
  ansible.builtin.file:
    path: '{{ [setup_user_result.home, ".ssh"] | path_join }}'
    state: directory
    mode: '700'

- name: Copy public keys to ssh folder
  ansible.builtin.copy:
    src: 'files/{{ item.public }}'
    dest: '{{ [setup_user_result.home, ".ssh", item.public] | path_join }}'
    mode: '444'
  loop: '{{ ssh.key_files }}'
  when: ssh.key_files is defined

- name: Copy private keys to ssh folder
  ansible.builtin.copy:
    src: 'files/{{ item.private }}'
    dest: '{{ [setup_user_result.home, ".ssh", item.private] | path_join }}'
    mode: '400'
  loop: '{{ ssh.key_files }}'
  when: ssh.key_files is defined
