# vim: ft=yaml.ansible
---

- name: Install avahi
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages:
      - avahi
      - nss-mdns

- name: Enable avahi systemd socket
  become: true
  ansible.builtin.systemd:
    name: 'avahi-daemon.socket'
    daemon_reload: true
    enabled: true

- name: Disable mDNS conflicting systemd-resolved service
  become: true
  ansible.builtin.systemd:
    name: 'systemd-resolved.service'
    enabled: false

- name: Apply nss config
  become: true
  ansible.builtin.template:
    src: 'avahi/nsswitch.conf.j2'
    dest: '/etc/nsswitch.conf'
    mode: '644'

- name: Permit traffic for avahi in home zone
  ansible.builtin.include_role:
    name: firewalld
    tasks_from: add_rule
  vars:
    zones:
      - home
      - trusted
