# vim: ft=yaml.ansible
---

- name: Install flatpak
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages:
      - flatpak
      - xdg-desktop-portal
      - flatpak-xdg-utils

- name: Add flathub remote
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: 'https://flathub.org/repo/flathub.flatpakrepo'

- name: Install flatpak apps
  become: true
  community.general.flatpak:
    name: '{{ apps.flatpak }}'
    remote: 'flathub'
  when: apps.flatpak is defined
