# vim: ft=yaml.ansible
---

- name: install flatpak
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - flatpak
      - xdg-desktop-portal
      - flatpak-xdg-utils
      - flatseal

- name: add flathub remote
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: 'https://flathub.org/repo/flathub.flatpakrepo'

- name: install flatpak apps
  become: true
  community.general.flatpak:
    name: '{{ apps.flatpak }}'
    remote: 'flathub'
  when: apps.flatpak is defined
