# vim: ft=yaml.ansible
---

- name: install z shell
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: zsh

- name: apply zshenv
  become: true
  ansible.builtin.template:
    src: 'zsh/zshenv.j2'
    dest: '/etc/zsh/zshenv'
    mode: '644'
