# vim: ft=yaml.ansible
---

- name: Install z shell
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages:
      - zsh
      - zsh-doc  # use `info zsh ...`

- name: Apply zshenv
  become: true
  ansible.builtin.template:
    src: 'zsh/zshenv.j2'
    dest: '/etc/zsh/zshenv'
    mode: '644'
