# vim: ft=yaml.ansible
---

- name: install rust toolchain
  become: true
  become_user: '{{ archconfig_user.name | default("archconfig") }}'
  ansible.builtin.command:
    cmd: 'rustup default stable'
  register: install_result
  changed_when: '"unchanged" not in (install_result.stdout_lines | last)'

- name: install paru
  become: true
  become_user: '{{ archconfig_user.name | default("archconfig") }}'
  kewlfft.aur.aur:
    use: makepkg
    name: paru

- name: backup paru.conf as .pacnew
  become: true
  ansible.builtin.copy:
    src: '/etc/paru.conf'
    dest: '/etc/paru.conf.pacnew'
    mode: preserve
    remote_src: true
    force: false

- name: apply paru.conf
  become: true
  ansible.builtin.template:
    src: 'paru/paru.conf.j2'
    dest: '/etc/paru.conf'
    mode: '644'
