# vim: ft=yaml.ansible
---

# TODO: split cli/gui packages (maybe depends on DE/WM config option)
- name: Install printer support packages
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages:
      - cups
      - cups-pdf
      - cups-pk-helper
      - lib32-libcups
      - ghostscript
      - gsfonts
      - gutenprint
      - hplip
      - hplip-plugin
      - foomatic-db
      - foomatic-db-gutenprint-ppds
      - python-pyqt5
      - python-pysmbc
      - python-reportlab
      - splix
      - system-config-printer  # FIXME: uses gtk3 gui

- name: Add user to groups for printing
  ansible.builtin.include_role:
    name: user
    tasks_from: user_add_group
  vars:
    user_new_groups:
      - lp
      - sys
      - cups

- name: Enable cups socket
  become: true
  ansible.builtin.systemd:
    name: 'cups.socket'
    daemon_reload: true
    enabled: true
