# vim: ft=yaml.ansible
---

# TODO: split cli/gui packages (maybe depends on DE/WM config option)
- name: install printer support packages
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    - cups
    - cups-pdf
    - cups-pk-helper
    - ghostscript
    - gsfonts
    - gutenprint
    - hplip
    - hplip-plugin
    - foomatic-db
    - foomatic-db-gutenprint-ppds
    - python-pyqt5
    - python-pysmbc
    - python-reportlab
    - splix
    - system-config-printer
    - print-manager
    - skanlite
    - skanpage

- name: enable cups socket
  ansible.builtin.systemd:
    name: 'cups.socket'
    daemon_reload: true
    enabled: true
