# vim: ft=yaml.ansible
---

- name: install pipewire and dependencies
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - pipewire
      - wireplumber
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
      - pipewire-v4l2
      # TODO: - pipewire-x11-bell
      # TODO: - pipewire-zeroconf
      - lib32-pipewire
      - lib32-pipewire-jack
      - lib32-pipewire-v4l2
      - pulsemixer
      - playerctl
#
# - name: apply playerctld service
#   become: true
#   ansible.builtin.template:
#     src: 'audio/playerctld.service.j2'
#     dest: '/etc/systemd/user/playerctld.service'
#     mode: '644'
#
# - name: enable playerctld service
#   ansible.builtin.systemd:
#     daemon_reload: true
#     name: playerctld.service
#     enabled: true
#     state: started
#     scope: user
