# vim: ft=yaml.ansible
---

- name: Install pipewire and dependencies
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - pipewire
      - wireplumber
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
      - pipewire-v4l2
      # TODO: - pipewire-x11-bell
      # TODO: - pipewire-zeroconf
      - lib32-pipewire
      - lib32-pipewire-jack
      - lib32-pipewire-v4l2
      - pulsemixer
      - playerctl

- name: Apply profile.d
  become: true
  ansible.builtin.template:
    src: 'audio/{{ item }}'
    dest: '/etc/profile.d/{{ item | splitext | first }}'
    mode: '644'
  with_items:
    - 60-pipewire.sh.j2

# - name: Apply playerctld service
#   become: true
#   ansible.builtin.template:
#     src: 'audio/playerctld.service.j2'
#     dest: '/etc/systemd/user/playerctld.service'
#     mode: '644'
#
# - name: Enable playerctld service
#   ansible.builtin.systemd:
#     daemon_reload: true
#     name: playerctld.service
#     enabled: true
#     state: started
#     scope: user
