# vim: ft=yaml.ansible
---

- name: Install pipewire and dependencies
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages:
      - pipewire
      - wireplumber
      - pipewire-alsa
      - pipewire-audio
      - pipewire-pulse
      - pipewire-jack
      - pipewire-roc
      - pipewire-v4l2
      - pipewire-x11-bell
      - pipewire-zeroconf
      - lib32-pipewire
      - lib32-pipewire-jack
      - lib32-pipewire-v4l2
      - pulsemixer
      # - playerctl
      - alsa-utils

- name: Apply profile.d
  become: true
  ansible.builtin.template:
    src: 'audio/{{ item }}.j2'
    dest: '/etc/profile.d/{{ item }}'
    mode: '644'
  with_items:
    - 60-pipewire.sh

- name: Create virtual mic
  become: true
  ansible.builtin.template:
    src: 'audio/30-loopback.sink.conf.j2'
    dest: '/etc/pipewire/pipewire.conf.d/30-loopback-sink.conf'
    mode: '644'

# - name: Apply playerctld service
#   become: true
#   ansible.builtin.template:
#     src: 'audio/playerctld.service.j2'
#     dest: '/etc/systemd/user/playerctld.service'
#     mode: '644'

# - name: Enable playerctld service
#   ansible.builtin.systemd:
#     daemon_reload: true
#     name: playerctld.service
#     enabled: true
#     scope: user

# - name: Install audiorelay
#   ansible.builtin.include_role:
#     name: pacman
#     tasks_from: install_pkg
#   vars:
#     packages:
#       - audiorelay
#   when: graphical_installed

# - name: Permit traffic for audiorelay in home zone
#   become: true
#   ansible.posix.firewalld:
#     zone: '{{ item.0 }}'
#     port: '59100/{{ item.1 }}'
#     permanent: true
#     state: enabled
#   vars:
#     zones: ['home', 'trusted']
#     protocols: ['tcp', 'udp']
#   loop: '{{ zones | product(protocols) | list }}'
