# vim: ft=yaml.ansible
---

- name: Install fwupd
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: fwupd

- name: Enable lvfs remote
  become: true
  ansible.builtin.command:
    argv: ['fwupdmgr', '-v', '-y', 'enable-remote', 'lvfs']
  register: enable_lvfs_result
  changed_when: "'::changed()' in enable_lvfs_result.stdout"
