# vim: ft=yaml.ansible
---

- name: Install fwupd
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages: fwupd

- name: Override UEFI mount point
  become: true
  community.general.ini_file:
    dest: '/etc/fwupd/uefi_capsule.conf'
    section: 'uefi_capsule'
    option: 'OverrideESPMountPoint'
    value: '/boot'
    mode: '644'
  notify:
    - Restart fwupd service

- name: Enable lvfs remote
  become: true
  ansible.builtin.command:
    argv: ['fwupdmgr', '-v', '-y', 'enable-remote', 'lvfs']
  register: enable_lvfs_result
  changed_when: "'::changed()' in enable_lvfs_result.stdout"
