# vim: ft=yaml.ansible
---

- name: archconfig user
  become: true
  ansible.builtin.user:
    name: '{{ archconfig_user.name | default("archconfig") }}'
    system: true
    shell: /usr/bin/nologin
    home: '{{ archconfig_user.home | default("/var/lib/archconfig") }}'
    create_home: true

- name: add archconfig user to sudoers
  become: true
  community.general.sudoers:
    name: archconfig
    user: '{{ archconfig_user.name | default("archconfig") }}'
    nopassword: true
    runas: 'ALL:ALL'
    commands: ALL
