# vim: ft=yaml.ansible
---

- name: install graphics drivers
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - mesa
      - vulkan-intel
      - intel-media-driver
      - lib32-mesa
      - lib32-vulkan-intel
