# vim: ft=yaml.ansible
---

- name: Install graphics drivers
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages:
      - mesa
      - xf86-video-intel
      - vulkan-intel
      - vulkan-icd-loader
      - intel-media-sdk
      - libva-utils
      - intel-gpu-tools
      - gstreamer-vaapi
      - lib32-mesa
      - lib32-vulkan-intel
      - lib32-vulkan-icd-loader
