# vim: ft=yaml.ansible
---
- name: Install git version of sddm
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - sddm-git  # TODO: use this, when upstream released and move it to task below

- name: Install plasma-desktop
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - plasma-meta
      - plasma-wayland-session
      - xorg-xwayland
      - wl-clipboard
      - wl-clipboard-x11
      - qt6-wayland
      - gtk-layer-shell
      - xdg-desktop-portal
      - xdg-desktop-portal-kde
      - xdg-desktop-portal-gtk
      - libappindicator-gtk3
      - libappindicator-gtk2
      - lib32-libappindicator-gtk3
      - lib32-libappindicator-gtk2
      # - sddm
      - breeze-grub  # TODO: set grub theme
      # KDE applications
      - konsole
      - dolphin
      - kdeconnect
      - gwenview
      - okular
      - kamoso
      - partitionmanager
      - spectacle
      - ksnip
      - kdialog
      - ark
      - filelight
      - kfind
      - krename
      - kwalletmanager
      - yakuake
      - kcharselect
      - kate
      - kcalc
      - kdebugsettings
      - keditbookmarks
      - kgpg
      - markdownpart
      - print-manager
      - skanlite
      - skanpage
      - kdegraphics-thumbnailers
      - svgpart
      # - kio-extras
      # - kio-gdrive
      - krdc
      - kdenetwork-filesharing
      # Games
      - kmines
      - kmahjongg
      - kshisen
      # Discover
      - packagekit-qt5

# TODO: use this somehow
- name: Set fact that graphical session is installed
  ansible.builtin.set_fact:
    graphical_installed: true

- name: Create SDDM config dir
  become: true
  ansible.builtin.file:
    dest: '/etc/sddm.conf.d'
    state: directory
    mode: '755'

# TODO: wayland version, auto-unlock kwallet
- name: Apply default SDDM config
  become: true
  ansible.builtin.template:
    src: 'plasma_desktop/00-default.conf.j2'
    dest: '/etc/sddm.conf.d/00-default.conf'
    mode: '644'

- name: Rotate second monitor
  become: true
  ansible.builtin.template:
    src: 'plasma_desktop/Xsetup.j2'
    dest: '/usr/bin/sddm_Xsetup'
    mode: '755'

- name: Link AccountService user avatar to .face
  become: true
  ansible.builtin.file:
    src: '/var/lib/AccountsService/icons/{{ user.name }}'
    dest: '/usr/share/sddm/faces/{{ user.name }}.face.icon'
    state: link
    follow: false
    force: true

- name: Enable SDDM
  become: true
  ansible.builtin.systemd:
    name: 'sddm.service'
    daemon_reload: true
    enabled: true
