# vim: ft=yaml.ansible
---

- name: Install packages
  become: true
  become_user: '{{ archconfig_user.name | default("archconfig") }}'
  ansible.builtin.command:
    argv: '{{ (sync_argv | default([pacman.executable | default("paru"), "--noconfirm", "--noprogressbar", "--needed",
      "--sync"])) + ([pacman_packages | mandatory] | flatten) }}'
    strip_empty_ends: true
  vars:
    pacman_packages: []
  register: paru_result
  changed_when: "'there is nothing to do' is not in (paru_result.stdout_lines | last)"
