# vim: ft=yaml.ansible
---

- name: install pacman/libalpm helpers and utils
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - pacman-contrib  # libalpm utils
      - pkgstats  # auto-submit and view archlinux package statistics
      - asp  # arch build sources management
      - devtools  # arch package build tools
      - namcap  # arch package analysis
      - expac  # query pacman database
      - downgrade  # ability to downgrade package(s)

- name: backup pacman.conf as .pacnew
  become: true
  ansible.builtin.copy:
    src: '/etc/pacman.conf'
    dest: '/etc/pacman.conf.pacnew'
    mode: preserve
    remote_src: true
    force: false

- name: apply pacman.conf
  become: true
  ansible.builtin.template:
    src: 'pacman/pacman.conf.j2'
    dest: '/etc/pacman.conf'
    mode: '644'

- name: apply mirrorlist
  become: true
  ansible.builtin.template:
    src: 'pacman/mirrorlist.j2'
    dest: '/etc/pacman.d/mirrorlist'
    mode: '644'

- name: backup makepkg.conf as .pacnew
  become: true
  ansible.builtin.copy:
    src: '/etc/makepkg.conf'
    dest: '/etc/makepkg.conf.pacnew'
    mode: preserve
    remote_src: true
    force: false

- name: apply makepkg.conf
  become: true
  ansible.builtin.template:
    src: 'pacman/makepkg.conf.j2'
    dest: '/etc/makepkg.conf'
    mode: '644'

- name: update package database
  become: true
  ansible.builtin.pacman:
    update_cache: true
