# vim: ft=yaml.ansible
---

- name: Apply mirrorlist
  become: true
  ansible.builtin.template:
    src: 'pacman/mirrorlist.j2'
    dest: '/etc/pacman.d/mirrorlist'
    mode: '644'

- name: Ensure pacman conf.d dir exists
  become: true
  ansible.builtin.file:
    path: '/etc/pacman.d/conf.d'
    state: directory
    mode: '755'

- name: Import chaotic pacman key
  become: true
  community.general.pacman_key:
    id: 'A3873AB27021C5DD39E0501AFBA220DFC880C036'
    keyserver: 'keyserver.ubuntu.com'

- name: Install chaotic mirrorlist and keyring
  become: true
  ansible.builtin.pacman:
    name:
      - 'https://geo-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
      - 'https://geo-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

- name: Apply pacman conf.d
  become: true
  ansible.builtin.template:
    src: 'pacman/{{ item }}'
    dest: '/etc/pacman.d/conf.d/{{ item | splitext | first }}'
    mode: '644'
  with_items:
    - 10-options.conf.j2
    - 20-multilib.conf.j2
    - 50-chaotic.conf.j2

- name: Include conf.d to pacman.conf
  become: true
  ansible.builtin.lineinfile:
    path: '/etc/pacman.conf'
    line: 'Include = /etc/pacman.d/conf.d/*.conf'

- name: Install libalpm packages
  become: true
  ansible.builtin.pacman:
    update_cache: true
    name:
      - pacman-contrib  # libalpm utils
      - pkgstats  # auto-submit and view archlinux package statistics
      - asp  # arch build sources management
      - expac  # query pacman database
      - downgrade  # ability to downgrade package(s)
      - reflector  # update archlinux mirrorlist
      - paru  # pacman aur helper
      - pkgfile  # packages metadata explorer

- name: Backup makepkg.conf as .pacnew
  become: true
  ansible.builtin.copy:
    src: '/etc/makepkg.conf'
    dest: '/etc/makepkg.conf.pacnew'
    mode: preserve
    remote_src: true
    force: false

- name: Apply makepkg.conf
  become: true
  ansible.builtin.template:
    src: 'pacman/makepkg.conf.j2'
    dest: '/etc/makepkg.conf'
    mode: '644'

- name: Apply reflector config
  become: true
  ansible.builtin.template:
    src: 'pacman/reflector.conf.j2'
    dest: '/etc/xdg/reflector/reflector.conf'
    mode: '644'

- name: Enable reflector timer
  become: true
  ansible.builtin.systemd:
    name: 'reflector.timer'
    daemon_reload: true
    enabled: true
    state: started

- name: Backup paru.conf as .pacnew
  become: true
  ansible.builtin.copy:
    src: '/etc/paru.conf'
    dest: '/etc/paru.conf.pacnew'
    mode: preserve
    remote_src: true
    force: false

- name: Apply paru.conf
  become: true
  ansible.builtin.template:
    src: 'pacman/paru.conf.j2'
    dest: '/etc/paru.conf'
    mode: '644'

- name: Enable pkgfile update timer
  become: true
  ansible.builtin.systemd:
    name: 'pkgfile-update.timer'
    enabled: true
    state: started
