# vim: ft=yaml.ansible
---

- name: Apply mirrorlists
  become: true
  ansible.builtin.template:
    src: 'pacman/{{ item }}.j2'
    dest: '/etc/pacman.d/{{ item }}'
    mode: '644'
  vars:
    mirrorlists:
      - mirrorlist
      - chaotic-mirrorlist
      # - alhp-mirrorlist
  loop: '{{ mirrorlists }}'

- name: Import chaotic pacman key
  become: true
  community.general.pacman_key:
    id: 'A3873AB27021C5DD39E0501AFBA220DFC880C036'
    keyserver: 'keyserver.ubuntu.com'

- name: Ensure pacman conf.d dir exists
  become: true
  ansible.builtin.file:
    path: '/etc/pacman.d/conf.d'
    state: directory
    mode: '755'

- name: Apply pacman conf.d
  become: true
  ansible.builtin.template:
    src: 'pacman/{{ item }}.j2'
    dest: '/etc/pacman.d/conf.d/{{ item }}'
    mode: '644'
  with_items:
    - 10-options.conf
    - 20-multilib.conf
    - 50-chaotic.conf

- name: Include conf.d to pacman.conf
  become: true
  ansible.builtin.lineinfile:
    path: '/etc/pacman.conf'
    line: 'Include = /etc/pacman.d/conf.d/*.conf'

- name: Install chaotic mirrorlist and keyring
  become: true
  community.general.pacman:
    update_cache: true
    name:
      - chaotic-keyring
      - chaotic-mirrorlist

# - name: Install ALHP mirrorlist and keyring
#   become: true
#   community.general.pacman:
#     name:
#       - alhp-keyring
#       - alhp-mirrorlist
#
# - name: Add ALHP repos before default
#   become: true
#   ansible.builtin.blockinfile:
#     path: '/etc/pacman.conf'
#     block: |
#       [core-x86-64-v3]
#       Include = /etc/pacman.d/alhp-mirrorlist
#
#       [extra-x86-64-v3]
#       Include = /etc/pacman.d/alhp-mirrorlist
#
#       [community-x86-64-v3]
#       Include = /etc/pacman.d/alhp-mirrorlist
#     insertbefore: '\[core\]'

- name: Install libalpm packages
  become: true
  community.general.pacman:
    name:
      - base-devel  # basic tools to build arch linux packages
      - pacman-contrib  # libalpm utils
      - pkgstats  # auto-submit and view archlinux package statistics
      - expac  # query pacman database
      - downgrade  # ability to downgrade package(s)
      - reflector  # update archlinux mirrorlist
      - paru  # pacman aur helper
      - pkgfile  # packages metadata explorer
      - devtools  # tools for package maintainers
      - namcap  # pacman package analyzer
      - pacutils  # helper tools for libalpm
      - check-broken-packages-pacman-hook-git  # check dynamic library, python and systemd dependencies

- name: Apply makepkg.conf
  become: true
  ansible.builtin.template:
    src: 'pacman/makepkg.conf.j2'
    dest: '/etc/makepkg.conf'
    mode: '644'

- name: Apply reflector config
  become: true
  ansible.builtin.template:
    src: 'pacman/reflector.conf.j2'
    dest: '/etc/xdg/reflector/reflector.conf'
    mode: '644'

- name: Enable reflector timer
  become: true
  ansible.builtin.systemd:
    name: 'reflector.timer'
    daemon_reload: true
    enabled: '{{ pacman.reflector | default(true) }}'
    state: '{{ pacman.reflector | default(true) | ternary("started", "stopped") }}'

- name: Apply paru.conf
  become: true
  ansible.builtin.template:
    src: 'pacman/paru.conf.j2'
    dest: '/etc/paru.conf'
    mode: '644'

- name: Enable pkgfile update timer
  become: true
  ansible.builtin.systemd:
    name: 'pkgfile-update.timer'
    enabled: true
    state: started
