# vim: ft=yaml.ansible
---

- name: Increase vm.max_map_count
  become: true
  ansible.posix.sysctl:
    name: 'vm.max_map_count'
    sysctl_file: '/etc/sysctl.d/50-increase-vm-max-map-count.conf'
    sysctl_set: true
    value: '2147483642'
