# vim: ft=yaml.ansible
---

- name: install developer tools
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - rustup
      - go
      - nodejs
      - npm
      - clang
      - php
      - php7
      - xdebug
      - composer
      - jdk-openjdk
      - jdk17-openjdk
      ## libs
      - python-aiohttp  # needed for codestats-relay
      ## lsp
      - lua-language-server
      - stylua
      - bash-language-server
      - shellcheck
      - shfmt
      - ansible-language-server
      - ansible-lint
      ### tools
      - aws-cli
      - web-ext  # web extension developer tools
      ## arch linux packaging
      - devtools  # arch package build tools
      - namcap  # arch package analysis

- name: stable rust toolchain as default
  ansible.builtin.command:
    cmd: 'rustup default stable'
  register: install_result
  changed_when: '"unchanged" not in (install_result.stdout_lines | last)'

- name: set default java toolchain
  become: true
  vars:
    java_version: 'java-17-openjdk'
  ansible.builtin.shell:
    executable: '/bin/bash'
    cmd: |
      set -Eeuxo pipefail
      prev_java_version="$(archlinux-java status | { grep default || true; })"
      archlinux-java set {{ java_version }}
      new_java_version="$(archlinux-java status | grep default)"
      if [ "$prev_java_version" != "$new_java_version" ]; then
        echo 'changed'
      fi
  register: set_java_result
  changed_when: "'changed' in set_java_result.stdout"

- name: apply profile.d
  become: true
  ansible.builtin.template:
    src: 'develop/{{ item }}'
    dest: '/etc/profile.d/{{ item | splitext | first }}'
    mode: '644'
  with_items:
    - 50-debuginfo.sh.j2
    - 50-java.sh.j2
    - 50-make.sh.j2
    - 50-rust.sh.j2
