# vim: ft=yaml.ansible
---

- name: Install tor packages
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages:
      - tor
      - torsocks
      - nyx
      - torbrowser-launcher

- name: Add user to tor group
  ansible.builtin.include_role:
    name: user
    tasks_from: user_add_group
  vars:
    new_groups: tor

- name: Ensure tor config dir
  become: true
  ansible.builtin.file:
    path: '/etc/torrc.d'
    state: directory
    mode: '755'

- name: Apply torrc.d configs
  become: true
  ansible.builtin.template:
    src: 'tor/{{ item }}.j2'
    dest: '/etc/torrc.d/{{ item }}'
    mode: '644'
  with_items:
    - control.conf
    - http-tunnel.conf

- name: Add torrc include
  become: true
  ansible.builtin.lineinfile:
    path: '/etc/tor/torrc'
    line: '%include /etc/torrc.d/*.conf'
    create: true
    mode: '644'
