# vim: ft=yaml.ansible
---

# TODO: https://wiki.archlinux.org/title/Tor#Transparent_Torification

- name: install tor packages
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      # - tor
      # - torsocks
      # - nyx
      - torbrowser-launcher

# - name: add user to tor group
#   ansible.builtin.include_role:
#     name: utils
#     tasks_from: user_add_group
#   vars:
#     new_groups: tor
