# vim: ft=yaml.ansible
---

- name: Apply mkinitcpio.conf
  become: true
  ansible.builtin.template:
    src: 'mkinitcpio/mkinitcpio.conf.j2'
    dest: '/etc/mkinitcpio.conf'
    mode: '644'
  notify:
    - run mkinitcpio
