# vim: ft=yaml.ansible
---

- name: Install nextdns
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: nextdns

- name: Apply nextdns config
  become: true
  ansible.builtin.template:
    src: 'nextdns/nextdns.conf.j2'
    dest: '/etc/nextdns.conf'
    mode: '644'

- name: Enable nextdns service
  become: true
  ansible.builtin.systemd:
    name: 'nextdns.service'
    enabled: true
    state: started
