# vim: ft=yaml.ansible
---

- name: install tmux
  ansible.builtin.import_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: tmux

- name: apply tmux.conf
  ansible.builtin.template:
    src: 'tmux/tmux.conf.j2'
    dest: '/etc/tmux.conf'
    mode: '644'
