# vim: ft=yaml.ansible
---

- name: Install tmux
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages: tmux

- name: Apply tmux.conf
  become: true
  ansible.builtin.template:
    src: 'tmux/tmux.conf.j2'
    dest: '/etc/tmux.conf'
    mode: '644'
