# vim: ft=yaml.ansible
---

- name: install tmux
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: tmux

- name: backup tmux.conf as .pacnew
  become: true
  ansible.builtin.copy:
    src: '/etc/tmux.conf'
    dest: '/etc/tmux.conf.pacnew'
    mode: preserve
    remote_src: true
    force: false

- name: apply tmux.conf
  become: true
  ansible.builtin.template:
    src: 'tmux/tmux.conf.j2'
    dest: '/etc/tmux.conf'
    mode: '644'
