# vim: ft=yaml.ansible
---

- name: Install libvirt
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages:
      - libvirt
      - dmidecode
      - dnsmasq
      - swtpm
      - qemu-desktop  # NOTE: qemu-base for non-gui setups
      - qemu-user
      - qemu-user-binfmt
      - qemu-system-x86
      - virt-manager
      - virt-viewer
      - virt-install

- name: Apply virtualization profile.d
  become: true
  ansible.builtin.template:
    src: 'virtualization/{{ item }}.j2'
    dest: '/etc/profile.d/{{ item }}'
    mode: '644'
  with_items:
    - 60-libvirt.sh

- name: Add user to libvirt group
  ansible.builtin.include_role:
    name: user
    tasks_from: user_add_group
  vars:
    user_new_groups:
      - libvirt
      - kvm

- name: Add libvirt-qemu user ACL to home dir
  ansible.posix.acl:
    path: '{{ "~" | expanduser }}'
    entity: libvirt-qemu
    etype: user
    permissions: x
    state: present

- name: Enable libvirt services
  become: true
  ansible.builtin.systemd:
    name: '{{ item }}'
    daemon_reload: true
    enabled: true
  with_items:
    - 'libvirtd.socket'
    - 'virtlogd.socket'
    - 'virtlockd.socket'
