# vim: ft=yaml.ansible
---

- name: Install libvirt
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - libvirt
      - dmidecode
      - dnsmasq
      - swtpm
      - qemu-desktop  # NOTE: qemu-base for non-gui setups
      - qemu-user
      - qemu-system-x86
      - virt-manager
      - virt-viewer
      - virt-install
      - vagrant

- name: Apply libvirt profile.d
  become: true
  ansible.builtin.template:
    src: 'virtualization/50-libvirt.sh.j2'
    dest: '/etc/profile.d/50-libvirt.sh'
    mode: '644'

- name: Add user to libvirt group
  ansible.builtin.include_role:
    name: utils
    tasks_from: user_add_group
  vars:
    new_groups: libvirt

- name: Enable libvirt services
  become: true
  ansible.builtin.systemd:
    name: '{{ item }}'
    daemon_reload: true
    enabled: true
  with_items:
    - 'libvirtd.socket'
    - 'virtlogd.socket'
    - 'virtlockd.socket'
