# vim: ft=yaml.ansible
---

- name: Add firewalld rules for services
  become: true
  ansible.posix.firewalld:
    zone: '{{ item.0 }}'
    service: '{{ item.1 }}'
    permanent: true
    immediate: true
    state: enabled
  vars:
    _zones: '{{ firewalld_zones | default(["home", "trusted"]) }}'
  loop: '{{ _zones | product(firewalld_services) | list }}'
  when: firewalld_services is defined

- name: Add firewalld rules for ports
  become: true
  ansible.posix.firewalld:
    zone: '{{ item.0 }}'
    port: '{{ item.1 }}'
    permanent: true
    immediate: true
    state: enabled
  vars:
    _zones: '{{ firewalld_zones | default(["home", "trusted"]) }}'
  loop: '{{ _zones | product(firewalld_ports) | list }}'
  when: firewalld_ports is defined
