# vim: ft=yaml.ansible
---

- name: Install firewalld
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - iptables-nft
      - firewalld

- name: Enable firewalld service
  become: true
  ansible.builtin.systemd:
    name: 'firewalld.service'
    enabled: true
    state: started
