# vim: ft=yaml.ansible
---

- name: Install firewalld
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages:
      - iptables-nft
      - firewalld
      # firewalld optional dependencies
      - gtk3
      - libnotify
      - nm-connection-editor
      - python-capng
      - python-pyqt5

- name: Enable firewalld service
  become: true
  ansible.builtin.systemd:
    name: 'firewalld.service'
    enabled: true
    state: started
