# vim: ft=yaml.ansible
---

- name: Install firewalld
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages:
      - iptables-nft
      - firewalld
      # firewalld optional dependencies
      - libnotify

- name: Create firewall group
  become: true
  ansible.builtin.group:
    name: firewall
    system: true

- name: Add user to 'firewall' group
  ansible.builtin.include_role:
    name: user
    tasks_from: user_add_group
  vars:
    new_groups: firewall

- name: Apply polkit rule
  become: true
  ansible.builtin.template:
    src: 'firewalld/50-org.fedoraproject.FirewallD1.rules.j2'
    dest: '/etc/polkit-1/rules.d/50-org.fedoraproject.FirewallD1.rules'
    mode: '644'

- name: Enable firewalld service
  become: true
  ansible.builtin.systemd:
    name: 'firewalld.service'
    enabled: true
    state: started
