# vim: ft=yaml.ansible
---

- name: install grub and breeze theme
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - grub
      - breeze-grub

- name: install grub efi application
  become: true
  ansible.builtin.command:
    cmd: 'grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB'
    creates: '/boot/grub/x86_64-efi/'
  notify:
    - generate grub configuration file

- name: create .pacnew backup of grub options
  become: true
  ansible.builtin.copy:
    src: '/etc/default/grub'
    dest: '/etc/default/grub.pacnew'
    mode: preserve
    remote_src: true
    force: false

- name: apply grub options
  become: true
  ansible.builtin.template:
    src: 'bootloader/grub.j2'
    dest: '/etc/default/grub'
    mode: '644'
  notify:
    - generate grub configuration file
