# vim: ft=yaml.ansible
---

- name: Set up grub
  when: bootloader.grub | default(true)
  ansible.builtin.include_tasks: grub.yml

- name: Set up systemd-boot
  when: not (bootloader.grub | default(true))
  ansible.builtin.include_tasks: systemd-boot.yml
