# vim: ft=yaml.ansible
---

- name: Install grub and breeze theme
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages:
      - '{{ bootloader.grub_package | default("grub") }}'
      - efibootmgr
      - breeze-grub

- name: Install grub efi application
  become: true
  ansible.builtin.command:
    cmd: 'grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB'
    creates: '/boot/grub/x86_64-efi/'
  notify:
    - Generate grub configuration file

- name: Apply grub options
  become: true
  ansible.builtin.template:
    src: 'bootloader/grub.j2'
    dest: '/etc/default/grub'
    mode: '644'
  notify:
    - Generate grub configuration file
