# vim: ft=yaml.ansible
---

- name: Install systemd-boot application
  become: true
  ansible.builtin.command:
    cmd: 'bootctl --path=/boot install'
    creates: '/boot/EFI/systemd/systemd-bootx64.efi'

- name: Add bootloader entries
  become: true
  ansible.builtin.template:
    src: 'bootloader/loader-entry.conf.j2'
    dest: '/boot/loader/entries/{{ item | kernel_package }}.conf'
    mode: '755'
  loop: '{{ kernels | to_kernel_list }}'

- name: Add bootloader fallback entries
  become: true
  ansible.builtin.template:
    src: 'bootloader/loader-entry.conf.j2'
    dest: '/boot/loader/entries/{{ item | kernel_package }}-fallback.conf'
    mode: '755'
  vars:
    fallback_entry: true
  loop: '{{ kernels | to_kernel_list }}'

- name: Bootloader config
  become: true
  ansible.builtin.template:
    src: 'bootloader/loader.conf.j2'
    dest: '/boot/loader/loader.conf'
    mode: '755'
