# vim: ft=yaml.ansible
---

- name: install realtime-privileges
  ansible.builtin.import_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: realtime-privileges

- name: add user to realtime group
  ansible.builtin.import_role:
    name: utils
    tasks_from: user_add_group
  vars:
    new_groups: realtime
