# vim: ft=yaml.ansible
---

- name: Install docker
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - docker
      - docker-compose
      - docker-scan
      - skopeo

- name: Add user to docker group
  ansible.builtin.include_role:
    name: utils
    tasks_from: user_add_group
  vars:
    new_groups: docker

- name: Enable docker socket
  become: true
  ansible.builtin.systemd:
    name: 'docker.socket'
    daemon_reload: true
    enabled: true
    state: started
