# vim: ft=yaml.ansible
---

- name: Install docker
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages:
      - docker
      - docker-buildx
      - docker-compose
      - docker-scan
      - skopeo
      - dive
      - lazydocker

- name: Apply profile.d
  become: true
  ansible.builtin.template:
    src: 'docker/{{ item }}.j2'
    dest: '/etc/profile.d/{{ item }}'
    mode: '644'
  with_items:
    - 50-docker.sh

- name: Add user to docker group
  ansible.builtin.include_role:
    name: user
    tasks_from: user_add_group
  vars:
    new_groups: docker

- name: Enable docker socket
  become: true
  ansible.builtin.systemd:
    name: 'docker.socket'
    daemon_reload: true
    enabled: true
    state: started
