# vim: ft=yaml.ansible
---

- name: Install base gui apps
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages:
      # ui toolkits
      - tk  # gitk
      - python-pyqt5

      # compatibility
      - wine-staging
      - wine-gecko
      - wine-mono

      # gui dev tools
      - kcachegrind
      - insomnia
      - visual-studio-code-bin
      - lapce
      - poedit
      - gource
      - imhex  # hex editor

      # office
      - libreoffice-fresh
      - tesseract  # text recognition (OCR)
      - tesseract-data-eng
      - tesseract-data-rus
      - tesseract-data-kaz
      - gimagereader-qt  # text recognition gui and scanner
      - obsidian
      - anki
      - sleek  # todo.txt manager

      # utils/tools
      - qalculate-qt  # qt frontend for qalculate
      - enpass-bin  # password manager
      - zenity  # gui dialogs in scripts
      - yad  # fork of zenity
      - xorg-xeyes  # xeyes, detect xwayland windows
      - dragon-drop  # drag-and-drop from/to terminal
      - corectrl  # control power/performance profiles
      - wev  # debug input events
      - klavaro  # touch typing tutor
      - linssid  # wifi scanner

      # multimedia
      - mpv  # multimedia player
      - mpv-mpris  # mpris plugin for mpv
      - mpv-sponsorblock  # block sponsored messages from youtube videos
      - imagemagick  # image processing
      - ffmpeg  # video processing
      - gstreamer
      - gstreamer-vaapi  # hardware acceleration
      - gst-libav
      - gst-plugins-base
      - gst-plugins-bad
      - gst-plugins-ugly
      - gst-plugins-good
      - gst-plugin-pipewire
      - gst-plugin-libcamera
      - lib32-gst-plugins-base
      - lib32-gst-plugins-good
      - easyeffects  # audio effects for pipewire apps
      - noisetorch  # noise suppression for microphone
      - qpwgraph  # pipewire gui patchbay
      - qt6-multimedia
      - qt6-multimedia-ffmpeg
      - qt6-multimedia-gstreamer
      - guvcview-qt  # webcam
      - ungoogled-chromium
      - appmenu-gtk-module  # fix failed to load module in chromium
      - gpu-screen-recorder-gtk-git
      - capnet-assist  # captive portal assistant
      - captive-browser-git  # chromium instance to log in to captive portals

      # social networks
      - telegram-desktop  # Telegram desktop client

      # torrent
      - qbittorrent

      # drawing tablet
      - xp-pen-tablet
      - opentabletdriver

      # graphical programs
      - gimp
      - inkscape
      - krita
      - pinta

      # android
      - scrcpy

      # video
      - v4l2loopback-dkms
      - obs-studio
      - obs-vaapi

      # separate role
      # - wireshark-qt  # TODO: add user to wireshark group
      # TODO: dosbox, 86box
      # - audiorelay  # TODO: open ports;

- name: Install gui apps
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages: '{{ apps.gui | default([]) }}'
  when: apps.gui is defined
