# vim: ft=yaml.ansible
---

- name: Install base gui apps
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages:
      # ui toolkits
      - tk  # gitk
      - python-pyqt5

      # compatibility
      - wine-staging
      - wine-gecko
      - wine-mono

      # gui dev tools
      - kcachegrind
      - visual-studio-code-bin
      - poedit
      - gource
      - imhex  # hex editor
      - kdbg

      # office
      - libreoffice-fresh
      - tesseract  # text recognition (OCR)
      - tesseract-data-eng
      - tesseract-data-rus
      - tesseract-data-kaz
      - gimagereader-qt  # text recognition gui and scanner
      - obsidian
      - anki

      # utils/tools
      - qalculate-qt  # qt frontend for qalculate
      - gnuplot  # plotting
      - enpass-bin  # password manager
      - zenity  # gui dialogs in scripts
      - yad  # fork of zenity
      - xorg-xeyes  # xeyes, xwininfo, xlsclients, detect xwayland windows
      - xorg-xwininfo
      - xorg-xlsclients
      - dragon-drop  # drag-and-drop from/to terminal
      - corectrl  # control power/performance profiles
      - wev  # debug input events
      - klavaro  # touch typing tutor
      - linssid  # wifi scanner
      - alacritty  # terminal emulator
      - waycheck  # check which wayland protocols are supported
      - deskflow  # software kvm
      - lan-mouse  # synergy alternative
      - crow-translate  # gui for text translation
      - gearlever  # install/update appimages
      - solaar  # manage Logitech keyboards, mice, and trackpads

      # multimedia
      - mpv  # multimedia player
      - mpv-mpris  # mpris plugin for mpv
      - mpv-sponsorblock  # block sponsored messages from youtube videos
      - mpv-uosc  # custom ui for mpv
      - imagemagick  # image processing
      - ffmpeg  # video processing
      - gstreamer
      - gstreamer-vaapi  # hardware acceleration
      - gst-libav
      - gst-plugins-base
      - gst-plugins-bad
      - gst-plugins-ugly
      - gst-plugins-good
      - gst-plugin-pipewire
      - gst-plugin-libcamera
      - lib32-gst-plugins-base
      - lib32-gst-plugins-good
      - easyeffects  # audio effects for pipewire apps
      - qpwgraph  # pipewire gui patchbay
      - qt6-multimedia
      - qt6-multimedia-ffmpeg
      - qt6-multimedia-gstreamer
      - guvcview-qt  # webcam
      - ungoogled-chromium-bin
      - gpu-screen-recorder-gtk
      - metadata-cleaner  # exif data cleaner from images and documents
      - yelp  # get help in gnome apps
      - audacity

      # network tools
      - capnet-assist  # captive portal assistant
      - wireshark-qt
      - remmina
      - freerdp
      - libvncserver
      - rustdesk-bin
      - anydesk-bin
      - carburetor  # gui for tractor onion router proxy
      - wifi-qr  # qr scan to connect or genearate to share wifi connection

      # social networks
      - telegram-desktop  # Telegram desktop client

      # torrent
      - qbittorrent
      - rqbit-desktop

      # graphical programs
      - gimp
      - inkscape
      - krita
      - python-legacy-cgi  # for python plugins of Krita
      - pinta
      - rnote  # graphical note taking app (for drawing tablets)
      - imv  # lightweight image viewer

      # android
      - scrcpy

      # password store
      - 1password

      # TODO: put in separate role (maybe separate gns3-server) + dependent roles (qemu/libvirt, docker, wireshark)
      - gns3-server  # network simulator
      - gns3-gui
      - dynamips
      - vpcs
      - ubridge

      # separate role
      # - wireshark-qt  # TODO: add user to wireshark group
      # TODO: dosbox, 86box
      # - audiorelay  # TODO: open ports;

- name: Install gui apps
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages: '{{ apps.gui | default([]) }}'
  when: apps.gui is defined
