# vim: ft=yaml.ansible
---

- name: Install gui apps
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: '{{ apps.gui | default([]) }}'
  when: apps.gui is defined
