# vim: ft=yaml.ansible
---

- name: install sway and dependencies
  ansible.builtin.import_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - sway
      - xorg-xwayland
      - swayidle
      - swaylock
      - swaybg
      - sway-systemd
      - swaykbdd
      - swayr
      - mako
      - libnotify
      - grim
      - slurp
      - i3status-rust
      - wofi
      - kanshi
      - wl-clipboard
      - wl-clipboard-x11
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal-gtk
        # dependency to blur background image
      - imagemagick

- name: create sway data dir
  ansible.builtin.file:
    path: '{{ xdg.home.data }}/sway'
    state: directory
    mode: '755'

- name: copy desktop background image
  ansible.builtin.copy:
    src: 'bg.jpg'
    dest: '{{ xdg.home.data }}/sway/bg.jpg'
    mode: '644'
  register: sway_bg_result

- name: create blurred background image
  ansible.builtin.command:
    cmd: 'convert {{ xdg.home.data }}/sway/bg.jpg -blur 0x50 -virtual-pixel edge {{ xdg.home.data }}/sway/bg-blurred.jpg'
  when: sway_bg_result.changed

- name: apply sway utils systemd services
  become: true
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '/etc/systemd/user/{{ item | basename | splitext | first }}'
    mode: '644'
  loop: '{{ [role_path, "templates/sway/*.service.j2"] | path_join | fileglob }}'

- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: sway utils systemd service
  ansible.builtin.systemd:
    name: '{{ item }}'
    enabled: true
    scope: user
  with_items:
    - swayidle.service
    - swaykbdd.service
    - swayrd.service
    - mako.service
    - kanshi.service
