# vim: ft=yaml.ansible
---

- name: Install sway and dependencies
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - sway
      - xorg-xwayland
      - swayidle
      - swaylock
      - swaybg
      - sway-systemd
      - swaykbdd
      - swayr
      - mako
      - wob
      - wdisplays
      - wlr-randr
      - wev
      - libnotify
      - grim
      - slurp
      - i3status-rust
      - wofi
      - kanshi
      - caffeinated
      - wl-clipboard
      - wl-clipboard-x11
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal-gtk
      - qt5-wayland
      - qt6-wayland
      - gtk-layer-shell
      # dependency to blur background image
      - imagemagick

- name: Ensure user local bin folder exists
  ansible.builtin.file:
    path: '~/.local/bin'
    state: directory
    mode: '755'

- name: Apply sway executable wrapper
  ansible.builtin.template:
    src: 'sway/sway.j2'
    dest: '~/.local/bin/sway'
    mode: '755'

- name: Create sway data dir
  ansible.builtin.file:
    path: '{{ xdg.home.data }}/sway'
    state: directory
    mode: '755'

- name: Copy desktop background image
  ansible.builtin.copy:
    src: 'bg.jpg'
    dest: '{{ xdg.home.data }}/sway/bg.jpg'
    mode: '644'
  notify: create blurred background image

- name: Apply sway utils systemd services
  become: true
  ansible.builtin.template:
    src: '{{ [role_path, "templates/sway", item] | path_join }}'
    dest: '/etc/systemd/user/{{ item | splitext | first }}'
    mode: '644'
  loop: '{{ [role_path, "templates/sway/*.service.j2"] | path_join | fileglob | map("basename") |
    difference([playbook_dir, "templates/sway/*.service.j2"] | path_join | fileglob | map("basename")) }}'

- name: Apply sway utils systemd services overrides
  become: true
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '/etc/systemd/user/{{ item | basename | splitext | first }}'
    mode: '644'
  loop: '{{ [playbook_dir, "templates/sway/*.service.j2"] | path_join | fileglob }}'

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Sway utils systemd services
  ansible.builtin.systemd:
    name: '{{ item | splitext | first }}'
    enabled: true
    scope: user
  vars:
    units:
      - swayrd.service
      - mako.service
  loop: '{{ units }}'

- name: Sway utils systemd custom services
  ansible.builtin.systemd:
    name: '{{ item | splitext | first }}'
    enabled: true
    scope: user
  loop: '{{ [role_path, "templates/sway/*.service.j2"] | path_join | fileglob | map("basename") |
    union([playbook_dir, "templates/sway/*.service.j2"] | path_join | fileglob | map("basename")) }}'
