# vim: ft=yaml.ansible
---

- name: Install base cli apps
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages:
      # core
      - ansible
      - python-passlib  # python crypt module is deprecated in Ansible
      - polkit

      # system debugging
      - acpica         # this two packages are needed for
      - python-pyudev  # amd_s2idle.py script

      # (un-)archiving tools
      - zip
      - unzip
      - p7zip
      - unrar
      - unarchiver

      # utils/tools
      - moreutils
      - dos2unix
      - ripgrep  # modern grep
      - ripgrep-all  # add multiple searchable formats for rg
      - lsd  # modern ls
      - tree  # output tree structure of fs
      - ictree  # generate tree output from stdin
      - fd  # modern find
      - jq  # json query processor
      - go-yq  # yaml query processor
      - htmlq  # html query processor
      - jless  # json viewer like less
      - fzf  # fuzzy menu
      - zoxide  # jump to directory like z
      - direnv  # shell extension that manages your env
      - vivid  # generate console colors
      - atuin  # shell history manager with sync
      - bat  # modern cat
      - glow  # cli markdown renderer
      - xplr  # cli file manager
      - dialog
      - s-tui  # stress testing
      - yt-dlp  # download youtube videos
      - upower  # power devices info
      - cpupower  # power management for cpu
      - udisks2  # disk management
      - ntfs-3g  # ntfs filesystem support
      - chezmoi  # dotfiles manager
      - dex  # execute desktop files and autostart apps
      - dust  # modern du
      - duf  # modern df
      - btop  # modern htop/top
      - rocm-smi-lib  # btop gpu support
      - brightnessctl  # backlight control
      - libqalculate  # cli qalculator
      - bc  # cli gnu calculator
      - cowsay
      - ponysay
      - pipe-rename  # rename your files using your favorite text editor
      - sad
      - yj
      - todotxt
      - jira-cli
      - b3sum
      - pv  # progress bar for commands
      - toilet
      - toilet-fonts
      - zap-bin  # AppImage package manager
      - ventoy-bin  # create multiboot live usb
      - ydotool  # systemd service (ydotoold)  # TODO: start/enable user service
      - toipe  # touch typing speed test
      - dhex  # hex editor
      - vt-cli  # virus total cli
      - perl-image-exiftool  # read/write file metadata
      - perl-archive-zip  # support zip-files in exiftool 👆
      - wavemon  # wifi scanner
      - mat2  # metadata cleaner
      - zellij  # terminal multiplexer
      - lemonade-bin  # remote clipboard daemon
      - paperkey  # export gnupg keys to paper
      - gpg-tui  # gnupg terminal user interface
      - rng-tools  # random generation tools
      - audio-share-bin  # share pc's audio over network to android  # TODO: open 65530 tcp/udp ports
      - evtest  # input device monitor/query
      - flite  # lightweight speech synthesis engine
      - mosh  # modern ssh

      # tex
      - tectonic

      # networking tools
      - curl
      - wget
      - httpie
      - nmap  # port scanner
      - openbsd-netcat  # network swiss army knife
      - socat  # multipurpose network relay
      - websocat  # websockets client (netcat/curl/socat)
      - net-tools  # netstat and friends
      - bind  # dns utils
      - dnslookup-bin  # nslookup with DoH, DoT support
      - inetutils  # network utils
      - traceroute
      - webtorrent-cli
      - nushell
      - miniserve  # local http file server
      - rsync
      - rclone
      - ffsend-bin
      - ngrep
      - dog  # dns client
      # TODO: wireguard vlan with egress (openziti, tailscale, zerotier, teleport, netmaker, firezone, etc.)

      # 2fa
      - libfido2
      - pam-u2f

      # qmk
      - zsa-udev
      - qmk
      - kanata-bin  # not QMK; but software analog to QMK

      # logitech pairing tool
      - ltunify

      # android
      - android-udev
      - android-tools

      # neovim
      - neovim  # neovim
      - bob  # neovim version manager
      - python-pynvim  # python 3 provider for neovim
      - neovim-drop-in  # drop-in replacement for vi/vim with neovim
      - nvimpager  # neovim based pager
      - vim-spell-en
      - vim-spell-ru
      - tree-sitter-bash
      - tree-sitter-c
      - tree-sitter-lua
      - tree-sitter-markdown
      - tree-sitter-python
      - tree-sitter-query
      - tree-sitter-vimdoc

      # kakoune
      - kakoune
      - kak-lsp
      - aspell
      - aspell-en
      - aspell-ru
      - editorconfig-core-c

      # document processors
      - pandoc

      # helix
      - helix

      # filesystems
      - btrfs-progs
      - udftools
      - compsize
      - exfatprogs

      # documentation
      - man-db
      - man-pages
      - arch-wiki-docs
      - arch-wiki-lite
      - tealdeer  # tldr
      - cheat-bin

      # bash
      - bash-completion  # bash shell completions
      - blesh  # bash line editor (readline replacement)
      - bash-preexec

      # dependencies
      - xxd-standalone  # needed for ncalayer to work
      - libpwquality  # optional for systemd -- password quality check

      # fingerprint
      - fprintd

      # password store
      - 1password-cli

      # themes
      - tokyonight-extra  # tokyonight theme for bunch of applications

- name: Install cli apps
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages: '{{ apps.cli | default([]) }}'
  when: apps.cli is defined
