# vim: ft=yaml.ansible
---

- name: Install base cli apps
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages:
      # core
      - ansible
      - python-passlib  # python crypt module is deprecated in Ansible
      - polkit

      # system debugging
      - acpica         # this two packages are needed for
      - python-pyudev  # amd_s2idle.py script

      # (un-)archiving tools
      - zip
      - unzip
      - 7zip
      - unrar
      - unarchiver

      # utils/tools
      - moreutils
      - dos2unix
      - ripgrep  # modern grep
      - sd  # modern sed
      - sad
      - lsd  # modern ls
      - tree  # output tree structure of fs
      - ictree  # generate tree output from stdin
      - fd  # modern find
      - jq  # json query processor
      - go-yq  # yaml query processor
      - htmlq  # html query processor
      - jless  # json viewer like less
      - fzf  # fuzzy menu
      - zoxide  # jump to directory like z
      - vivid  # generate console colors
      - bat  # modern cat
      - glow  # cli markdown renderer
      - xplr  # cli file manager
      - dialog
      - s-tui  # stress testing
      - yt-dlp  # download youtube videos
      - upower  # power devices info
      - udisks2  # disk management
      - ntfs-3g  # ntfs filesystem support
      - chezmoi  # dotfiles manager
      - dex  # execute desktop files and autostart apps
      - dust  # modern du
      - ncdu  # classic ncurses du
      - diskonaut  # cli alternative of disksniffer
      - duf  # modern df
      - htop
      - btop  # modern htop/top
      - rocm-smi-lib  # btop gpu support
      - brightnessctl  # backlight control
      - libqalculate  # cli qalculator
      - bc  # cli gnu calculator
      - cowsay
      - ponysay
      - pipe-rename  # rename your files using your favorite text editor
      - yj
      - todotxt
      - jira-cli
      - b3sum
      - pv  # progress bar for commands
      - toilet
      - toilet-fonts
      - zap-bin  # AppImage package manager
      - ventoy-bin  # create multiboot live usb
      - ydotool  # systemd service (ydotoold)  # TODO: start/enable user service
      - toipe  # touch typing speed test
      - dhex  # hex editor
      - vt-cli  # virus total cli
      - perl-image-exiftool  # read/write file metadata
      - perl-archive-zip  # support zip-files in exiftool 👆
      - wavemon  # wifi scanner
      - mat2  # metadata cleaner
      - zellij  # terminal multiplexer
      - lemonade-bin  # remote clipboard daemon  # TODO: move/create to role; take service file from dotfiles
      - paperkey  # export gnupg keys to paper
      - gpg-tui  # gnupg terminal user interface
      - rng-tools  # random generation tools
      - audio-share-bin  # share pc's audio over network to android  # TODO: open 65530 tcp/udp ports
      - evtest  # input device monitor/query
      - flite  # lightweight speech synthesis engine
      - mosh  # modern ssh
      - graphviz
      - chafa  # terminal image viewer (converts to ascii/unicode symbols)
      - gptfdisk  # gdisk util
      - time  # monitor program's use of system resources
      - python-j2cli  # jinja2 cli
      - just  # tool save and run project-specific commands
      - ansifilter  # remove or convert ANSI codes to another format
      - strace  # userspace tracer
      - xdg-ninja  # detect dotfiles, which can be moved to xdg base dirs
      - translate-shell  # google translate from shell
      - rlwrap  # adds readline-style editing and history to programs
      - systemctl-tui
      - gum  # ui for shell scripts
      - entr  # run command on file change

      # video
      - v4l-utils
      - v4l2loopback-dkms
      - v4l2loopback-utils

      # tex
      - tectonic

      # networking tools
      - curl
      - wget
      - httpie
      - nmap  # port scanner
      - openbsd-netcat  # network swiss army knife
      - socat  # multipurpose network relay
      - websocat  # websockets client (netcat/curl/socat)
      - net-tools  # netstat and friends
      - bind  # dns utils
      - dnslookup-bin  # nslookup with DoH, DoT support
      - inetutils  # network utils
      - traceroute
      - webtorrent-cli
      - miniserve  # local http file server
      - rsync
      - rclone
      - ffsend-bin
      - ngrep
      - dog  # dns client
      - ookla-speedtest-bin
      - iperf3  # network bandwith measurement tool
      - whois
      - lynx  # terminal browser
      - tractor  # onion router proxy
      - rqbit  # cli torrent client
      - mtr  # ping + traceroute
      - tcpdump
      # TODO: wireguard vlan with egress (openziti, tailscale, zerotier, teleport, netmaker, firezone, etc.)

      # 2fa
      - libfido2
      - pam-u2f

      # qmk
      - zsa-udev
      - qmk
      - kanata-bin  # not QMK; but software analog to QMK

      # logitech pairing tool
      - ltunify

      # android
      - android-udev
      - android-tools

      # kakoune
      - kakoune
      - kak-lsp
      - aspell
      - aspell-en
      - aspell-ru
      - editorconfig-core-c

      # document processors
      - pandoc

      # helix
      - helix

      # filesystems
      - btrfs-progs
      - udftools
      - compsize
      - exfatprogs

      # documentation
      - man-db
      - man-pages
      - arch-wiki-docs
      - arch-wiki-lite
      - tealdeer  # TODO: checkout official tldr client https://github.com/tldr-pages/tlrc
      - halp  # automatically check options for help in cli programs
      - cheat-bin

      # internet
      - tg-notify  # notification through Telegram Bot

      # shell tools
      - bash-completion  # bash shell completions
      - blesh  # bash line editor (readline replacement)
      - bash-preexec
      - direnv  # shell extension that manages your env
      - atuin  # shell history manager with sync
      - starship  # shell prompt
      - navi  # interactive cheatsheets
      - nushell
      - sheldon  # shell plugin manager
      - sshx  # web collaborative terminal

      # dependencies
      - tinyxxd  # needed for ncalayer to work
      - libpwquality  # optional for systemd -- password quality check

      # fingerprint
      - fprintd

      # password store
      - 1password-cli

      # themes
      - tokyonight-extra  # tokyonight theme for bunch of applications

- name: Install cli apps
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    pacman_packages: '{{ apps.cli | default([]) }}'
  when: apps.cli is defined
