# vim: ft=yaml.ansible
---

- name: Install cli apps
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: '{{ apps.cli | default([]) }}'
  when: apps.cli is defined
