# vim: ft=yaml.ansible
---

- name: install ly display manager
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: ly

- name: backup ly config as .pacnew
  become: true
  ansible.builtin.copy:
    src: '/etc/ly/config.ini'
    dest: '/etc/ly/config.ini.pacnew'
    mode: preserve
    remote_src: true
    force: false

- name: apply ly config
  become: true
  ansible.builtin.template:
    src: 'ly/config.ini.j2'
    dest: '/etc/ly/config.ini'
    mode: '755'

- name: enable ly display manager
  become: true
  ansible.builtin.systemd:
    name: 'ly'
    daemon_reload: true
    enabled: '{{ ly is defined and ly is truthy }}'
