# vim: ft=yaml.ansible
---

- name: Install networkmanager
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages:
      - networkmanager
      - wireless-regdb
      # IPSec
      - networkmanager-l2tp
      - strongswan

- name: Add user to 'network' group
  ansible.builtin.include_role:
    name: user
    tasks_from: user_add_group
  vars:
    new_groups: network

- name: Apply rules.d
  become: true
  ansible.builtin.template:
    src: 'networkmanager/50-org.freedesktop.NetworkManager.rules.j2'
    dest: '/etc/polkit-1/rules.d/50-org.freedesktop.NetworkManager.rules'
    mode: '644'
