# vim: ft=yaml.ansible
---

- name: Install snapper and pacman/grub addons
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages:
      - snapper
      - snp  # create snapshot before/after command execution
      - snap-pac
      - grub-btrfs
      - inotify-tools
      - snap-pac-grub
      - snapper-rollback

- name: Ensure snapshots folder
  become: true
  ansible.builtin.file:
    path: '/.snapshots'
    state: directory
    group: 'wheel'
    mode: '750'

- name: Apply config for root
  become: true
  ansible.builtin.template:
    src: 'snapper/root.j2'
    dest: '/etc/snapper/configs/root'
    mode: '640'

- name: Apply snapper config
  become: true
  ansible.builtin.template:
    src: 'snapper/snapper.j2'
    dest: '/etc/conf.d/snapper'
    mode: '640'

- name: Apply grub-btrfs config
  become: true
  ansible.builtin.template:
    src: 'snapper/grub-btrfs.j2'
    dest: '/etc/default/grub-btrfs/config'
    mode: '644'

- name: Enable grub-btrfsd service
  become: true
  ansible.builtin.systemd:
    name: 'grub-btrfsd.service'
    daemon_reload: true
    enabled: true

- name: Enable snapper systemd timer
  become: true
  ansible.builtin.systemd:
    name: 'snapper-timeline.timer'
    daemon_reload: true
    enabled: true

- name: Enable snapper cleanup systemd timer
  become: true
  ansible.builtin.systemd:
    name: 'snapper-cleanup.timer'
    daemon_reload: true
    enabled: true
