# vim: ft=yaml.ansible
---

- name: install kernels
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: '{{ kernels | to_kernel_list | map("kernel_package") }}'

- name: install microcode
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: '{{ ucode }}'
  when: ucode is defined

- name: install kernel pacman hook
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: mkmm

- name: ensure that hook dir exists
  become: true
  ansible.builtin.file:
    path: '/etc/pacman.d/hooks'
    state: directory
    mode: '755'

- name: enable pacman hooks
  become: true
  ansible.builtin.file:
    src: '/usr/share/mkmm/{{ item.src }}.hook'
    dest: '/etc/pacman.d/hooks/{{ item.dest }}.hook'
    state: link
  with_items:
    - src: 10-mkmm-tmpfs-pre
      dest: 10-mkmm-tmpfs-pre
    - src: 10-mkmm-tmpfs-post
      dest: za-mkmm-tmpfs-post  # TODO: don't touch order of hooks if ever found a workaround

- name: install mkmm bleach service
  become: true
  ansible.builtin.systemd:
    name: 'mkmm-bleach.service'
    enabled: true
