# vim: ft=yaml.ansible
---

- name: Install kernels
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: '{{ kernels | to_kernel_list | map("kernel_package") }}'

- name: Install kernel headers
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: '{{ kernels | to_kernel_list | map("kernel_headers") }}'
  when: kernel_headers is defined and kernel_headers

- name: Install extra kernel packages (modules, etc)
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: '{{ [kernel_extra_modules] | flatten }}'

- name: Install microcode
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: '{{ ucode }}'
  when: ucode is defined

- name: Install kernel pacman hook
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: mkmm

- name: Ensure that hook dir exists
  become: true
  ansible.builtin.file:
    path: '/etc/pacman.d/hooks'
    state: directory
    mode: '755'

- name: Enable pacman hooks
  become: true
  ansible.builtin.file:
    src: '/usr/share/mkmm/{{ item.src }}.hook'
    dest: '/etc/pacman.d/hooks/{{ item.dest }}.hook'
    state: link
  with_items:
    - src: 10-mkmm-tmpfs-pre
      dest: 10-mkmm-tmpfs-pre
    - src: 10-mkmm-tmpfs-post
      dest: za-mkmm-tmpfs-post  # TODO: don't touch order of hooks if ever found a workaround

- name: Install mkmm bleach service
  become: true
  ansible.builtin.systemd:
    name: 'mkmm-bleach.service'
    enabled: true
