# vim: ft=yaml.ansible
---

- name: Install kernels
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages: '{{ kernels.list | default(["linux"]) }}'

- name: Install kernel headers
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages: '{{ kernels.list | default(["linux"]) | product(["headers"]) | map("join", "-") }}'
  when: kernels.headers is defined and kernels.headers

- name: Install firmware package
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages: linux-firmware

- name: Install extra kernel packages (modules, etc)
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages: '{{ [kernels.extra_modules] | default([]) | flatten }}'

- name: Install microcode
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages: '{{ kernels.microcode }}'
  when: kernels.microcode is defined

- name: Install kernel pacman hook
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages: mkmm

- name: Ensure that hook dir exists
  become: true
  ansible.builtin.file:
    path: '/etc/pacman.d/hooks'
    state: directory
    mode: '755'

- name: Enable pacman hooks
  become: true
  ansible.builtin.file:
    src: '/usr/share/mkmm/{{ item }}.hook'
    dest: '/etc/pacman.d/hooks/{{ item }}.hook'
    state: link
  with_items:
    - 10-mkmm-tmpfs-pre
    - 65-mkmm-tmpfs-post

- name: Install mkmm bleach service
  become: true
  ansible.builtin.systemd:
    name: 'mkmm-bleach.service'
    enabled: true

- name: Add/remove kernel modules
  become: true
  community.general.modprobe:
    name: '{{ item.name }}'
    params: '{{ item.params | default(omit) }}'
    persistent: '{{ item.state | default("present") }}'
    state: '{{ item.state | default("present") }}'
  loop: '{{ kernels.modprobe }}'
  when: kernels.modprobe is defined
