# vim: ft=yaml.ansible
---

- name: install kernels
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: '{{ kernels | to_kernel_list | map("kernel_package") }}'

- name: install microcode
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: '{{ ucode }}'
  when: ucode is defined

- name: install kernel pacman hook
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages: mkmm
#
# - name: ensure that hook dir exists
#   become: true
#   ansible.builtin.file:
#     path: '/etc/pacman.d/hooks'
#     state: directory
#     mode: '755'

- name: enable pacman hooks
  become: true
  ansible.builtin.file:
    src: '/usr/share/mkmm/10-mkmm-tmpfs-{{ item }}.hook'
    dest: '/etc/pacman.d/hooks/10-mkmm-tmpfs-{{ item }}.hook'
    state: link
  with_items:
    - pre
    - post

- name: install mkmm bleach service
  become: true
  ansible.builtin.systemd:
    name: 'mkmm-bleach.service'
    enabled: true
