# vim: ft=yaml.ansible
---

- name: install noto, fira-code, nerd and twemoji fonts
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - ttf-fira-code
      - noto-fonts
      - ttf-nerd-fonts-symbols
      - ttf-twemoji
