# vim: ft=yaml.ansible
---

- name: Install noto, fira-code, nerd and twemoji fonts
  ansible.builtin.include_role:
    name: pacman
    tasks_from: install_pkg
  vars:
    packages:
      - ttf-fira-code
      - ttf-jetbrains-mono
      - noto-fonts
      - ttf-liberation
      - ttf-croscore
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-mono
      - ttf-joypixels
      - ttf-ms-fonts
      - ttf-carlito
      - ttf-caladea

- name: Link nerd fonts config
  become: true
  ansible.builtin.file:
    src: '/usr/share/fontconfig/conf.avail/10-nerd-font-symbols.conf'
    dest: '/etc/fonts/conf.d/10-nerd-font-symbols.conf'
    state: link
