# vim: ft=yaml.ansible
---

- name: Install noto, fira-code, nerd and twemoji fonts
  ansible.builtin.include_role:
    name: utils
    tasks_from: install_pkg
  vars:
    packages:
      - ttf-fira-code
      - noto-fonts
      - ttf-nerd-fonts-symbols-2048-em
      - ttf-twemoji

- name: Link nerd fonts config
  become: true
  ansible.builtin.file:
    src: '/usr/share/fontconfig/conf.avail/10-nerd-font-symbols.conf'
    dest: '/etc/fonts/conf.d/10-nerd-font-symbols.conf'
    state: link

- name: Link twemoji config
  become: true
  ansible.builtin.file:
    src: '/usr/share/fontconfig/conf.avail/75-twemoji.conf'
    dest: '/etc/fonts/conf.d/75-twemoji.conf'
    state: link
